### ISSUE TITLE
[FEATURE] Support Spark3.4

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1006]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Spark 3.4.1 has been released. It's time to support in uniffle side. https://spark.apache.org/releases/spark-release-3-4-0.html

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by summaryzb** [comment]
Volunteering

**Comment by zuston** [comment]
> Volunteering

Thanks!
