### ISSUE TITLE
[Improvement] [tez]：Optimize user switch to shuffle mode local/remote.

### ISSUE THREAD

**Issue by baitian77** [apache/incubator-uniffle#1024]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, users need to set the parameter tez.am.launch.launch.cmd-opts to switch between local shuffle and remote shuffle, but this parameter is difficult for users to understand.   
We need a simpler and easier to understand parameter，such as tez.shuffle.mode = local/remote

### How should we improve?

1. set tez.am.launch.launch.cmd-opts=-XX:+PrintGCDetails -verbose:gc -XX:+PrintGCTimeStamps -XX:+UseNUMA -XX:+UseParallelGC org.apache.tez.dag.app.RssDAGAppMaster。 【 note： this config will not change 】
2. add new conf tez.shuffle.mode  which will used in RssDAGAppMaster.  when this conf equal local,  RssDAGAppMaster will use all DAGAppMaster  functions

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Could we do similar things in another class? Maybe you can refer to `DelegationRssShuffleManager` in our project.
