### ISSUE TITLE
[Improvement] Add LICENSE-binary

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1044]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For binary release, we should addd LICENSE-binary.

### How should we improve?

We should add LICENSE-binary. https://github.com/apache/spark/blob/master/LICENSE-binary

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@LuciferYang Could you help me?

**Comment by LuciferYang** [comment]
What kind of help do you need? @jerqi

**Comment by jerqi** [comment]
> What kind of help do you need? @jerqi

Could you finish this issue refer to Spark's behaviour?

**Comment by LuciferYang** [comment]
Ok, let me investigate first
