### ISSUE TITLE
[DOCS] Add the document for Netty

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1060]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

We don't have the document to tell users how to use Netty to transfer data.

### Affects Version(s)

master

### Improving the documentation

server_guide.md
client_guide.md

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@leixm Could you help me with this issue?

**Comment by leixm** [comment]
I will raise a PR later.
