### ISSUE TITLE
[Bug] incubator-uniffle-website codes can not clone in windows

### ISSUE THREAD

**Issue by cdmikechen** [apache/incubator-uniffle#1061]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

It is currently not possible to clone `https://github.com/apache/incubator-uniffle-website` locally
```shell
$ git clone https://github.com/cdmikechen/incubator-uniffle-website.git
Cloning into 'incubator-uniffle-website'...
remote: Enumerating objects: 396, done.
remote: Counting objects: 100% (171/171), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 396 (delta 81), reused 128 (delta 62), pack-reused 225
Receiving objects: 100% (396/396), 2.59 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (166/166), done.
error: invalid path 'blog/2023-07-21/Uniffle: New chapter for the shuffle in the cloud native era.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```

### Affects Version(s)

master

### Additional context

It seems to be caused by colon/spaces in the file path. I'm using windows.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
closed.
