### ISSUE TITLE
[FEATURE]  Support Spark 3.5

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1083]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Spark 3.5 is releasing. We should support the version.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@LuciferYang @summaryzb Could you help me with this issue?

**Comment by summaryzb** [comment]
volunteering

**Comment by summaryzb** [comment]
Once spark3.5 release, i'll move on

**Comment by LuciferYang** [comment]
@summaryzb Apache Spark 3.5.0 has been released to the Maven Central Repository.
