### ISSUE TITLE
[FEATURE] Support dynamic allocation for Gluten Uniffle

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1087]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

As the comment https://github.com/oap-project/gluten/pull/1966#discussion_r1230611154
We should support dynamic allocation for Gluten.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@summaryzb @LuciferYang Could you help me with this issue?

**Comment by summaryzb** [comment]
volunteering
