### ISSUE TITLE
[DOCS] Split the client.md into four documents

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1094]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

The `docs/client.md` have common client's, Spark's, MapReduce's and Tez's configurations. We should split it into four documents.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ASDasd341** [comment]
Let me help in this.

**Comment by jerqi** [comment]
Thanks.

**Comment by zivali** [comment]
Hi @jerqi, may I try this one? 
Will try to preserve only [shared configuration](https://github.com/apache/incubator-uniffle/blob/master/docs/client_guide.md#common-setting) in [client_guide.md](https://github.com/apache/incubator-uniffle/blob/master/docs/client_guide.md#deploy-tez-client-plugin) and open three other subpages:
- Deploy Spark Client Plugin & Configurations
- Deploy MapReduce Client Plugin & Configurations
- Deploy Tez Client Plugin & Configurations

**Comment by jerqi** [comment]
> Hi @jerqi, may I try this one? Will try to preserve only [shared configuration](https://github.com/apache/incubator-uniffle/blob/master/docs/client_guide.md#common-setting) in [client_guide.md](https://github.com/apache/incubator-uniffle/blob/master/docs/client_guide.md#deploy-tez-client-plugin) and open three other subpages:
> 
> * Deploy Spark Client Plugin & Configurations
> * Deploy MapReduce Client Plugin & Configurations
> * Deploy Tez Client Plugin & Configurations

OK.
