### ISSUE TITLE
[DOCS]  Add slack link to the `readme.md`

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1095]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

Our slack link is https://join.slack.com/t/the-asf/shared_invite/zt-1fm9561yr-uzTpjqg3jf5nxSJV5AE3KQ
We can refer to https://github.com/apache/iceberg/blob/4f401a7779a56c25e9371cc3a95a13a51012cd6c/README.md?plain=1#L24

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ASDasd341** [comment]
i can do that.

**Comment by jerqi** [comment]
Thanks.
