### ISSUE TITLE
[FEATURE] Add labels with disk path for local storage `total_localfile_write_data` metrics

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1108]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently, the metric of `total_localfile_write_data` only shows the all disks data written. It's better to expose the every disk's uniffle data written size.

We could put the disk path as the label of `total_localfile_write_data` metrics

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhuyaogai** [comment]
@zuston Could you assign this issue to me?

**Comment by zuston** [comment]
> @zuston Could you assign this issue to me?

Thanks. Pls go ahead
