### ISSUE TITLE
[Improvement] Explicitly throw `BUFFER_LIMIT_OF_HUGE_PARTITION` instead of `NO_BUFFER`

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1119]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In current codebase, once the huge partition is limited of fixed memory, the NO_BUFFER code will be returned. It's better to throw explicit huge partition limit code and log this in client side. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
BTW. the code of https://github.com/apache/incubator-uniffle/blob/ca245316c3f5002de117adb7f550d3198fb7f6e2/server/src/main/java/org/apache/uniffle/server/ShuffleTaskManager.java#L410-L440 looks strange. It's better to throw `NoBufferException` or `NoRegisterException`  instead of using the negative number to indicate the error.

**Comment by SunMoon97** [comment]
@jerqi can you assign me this issue?
