### ISSUE TITLE
[Improvement] Unregister shuffle explicitly when Spark application is stopped

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1132]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now we delete  shuffle data when the shuffle servers haven't received heartbeat for a period time and trigger to delete the shuffle data because of heartbeat time out.
We can unregister shuffle explicitly when Spark application is stopped.
MR and Tez have supported this feature. Spark can support it, too. You can refer to https://github.com/apache/incubator-uniffle/pull/1131

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhuyaogai** [comment]
@jerqi Could you assign this issue to me?
