### ISSUE TITLE
[Improvement] Can we support AE of SPARK2.4

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#114]
At present, Spark does not support AE in version 2.4, should it be supported? Or are there any reasons why it is not supported?

**Comment by colinmjj** [comment]
I think AE is an experience feature in Spark 2.4, and it was officially announced in Spark 3.
So it isn't planned to be supported in Spark 2.4 in short term, but anyone is welcome to contribute this feature if interested.

**Comment by jerqi** [comment]
AE of Spark 2.4 isn't a complete feature. We shouldn't support it.
