### ISSUE TITLE
[Bug] GC logs in JDK 11 do not include date and time stamps.

### ISSUE THREAD

**Issue by qijiale76** [apache/incubator-uniffle#1149]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Now gc log in jdk11 is set by 
``` shell
JVM_ARGS=" -server \
......
          -Xloggc:${RSS_LOG_DIR}/gc-%t.log"

JAVA11_EXTRA_ARGS=" -XX:+IgnoreUnrecognizedVMOptions \
          -Xlog:gc:tags,time,uptime,level"
```
and gc log do not include data and time 
```
[0.004s][info][gc,heap] Heap region size: 32M
```
when use
```
-Xlog:gc*:${RSS_LOG_DIR}/gc-%t.log:tags,time,uptime,level
```
it works
```
[2023-08-15T16:16:50.442+0800][0.011s][info   ][gc,heap] Heap region size: 32M
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by lifeSo** [comment]
@qijiale76 
Hei, Is this problem resolved ?
