### ISSUE TITLE
[Bug] [TEZ] The container does not exit because shuffleclient is not closed

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1157]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

MR has fixed the issue https://github.com/apache/incubator-uniffle/pull/882
Tez has the similar issue. We can refer to https://github.com/apache/incubator-uniffle/pull/882 to fix the issue.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhuyaogai** [comment]
@jerqi Could you assign this issue to me?

**Comment by Sanjeevliv** [comment]
Please assign it to me

**Comment by jerqi** [comment]
> Please assign it to me

Assigned. Thanks.
