### ISSUE TITLE
Netty performance tracking

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1161]
### sub tasks

1. #1162 
2. #1163

### Benchmark

Tested with grpc and netty.

#### Environment
_Software_: Uniffle master / Hadoop 3.2.2 / Spark 3.1.2

_Hardware_: Machine 96 cores, 512G memory, 1T * 4 SSD, network bandwidth 8GB/s

_Hadoop Yarn Cluster_: 1 * ResourceManager + 40 * NodeManager, every machine 1T * 4 SSD

_Uniffle Cluster_: 1 * Coordinator + 5 * Shuffle Server, every machine 1T * 4 SSD

#### Configuration
spark's conf
``` 
spark.executor.instances 400
spark.executor.cores 1
spark.executor.memory 2g
spark.shuffle.manager org.apache.spark.shuffle.RssShuffleManager
spark.rss.storage.type MEMORY_LOCALFILE
``` 

uniffle grpc-based server's conf
``` 
JVM XMX=200g

...
rss.server.buffer.capacity 100g
rss.server.read.buffer.capacity 20g
rss.server.flush.thread.alive 20
rss.server.flush.threadPool.size 50
rss.server.high.watermark.write 80
rss.server.low.watermark.write 70
...
``` 

uniffle netty-based server's conf
``` 
XMX_SIZE="140g"
MAX_DIRECT_MEMORY_SIZE=200g

...
rss.server.buffer.capacity 100g
rss.server.read.buffer.capacity 20g
rss.server.flush.thread.alive 20
rss.server.flush.threadPool.size 50
rss.server.high.watermark.write 80
rss.server.low.watermark.write 70
...
``` 

#### report

| type                | 5T (run with 400 executors) |
|----------------------:|:---------------------------:|
| grpc-based | 3.6min/5.9min    |
| netty                    | 3.4min/7.7min   |

And I found the spark executor with netty uniffle gc time is higher than grpc based.

**Comment by jerqi** [comment]
Could you enable `spark.rss.client.off.heap.memory.enable`?

**Comment by zuston** [comment]
> Could you enable `spark.rss.client.off.heap.memory.enable`?

This is only for hdfs.

**Comment by zuston** [comment]
Another problem: the remote fetch from localfile is unstable, compared with grpc, it costs too much time.
