### ISSUE TITLE
Exposing the `getDataLen` method for ShuffleDataResult

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#1164]
Why not exposing the `bufferDataLen` method for being invoked?

_Originally posted by @zuston in https://github.com/apache/incubator-uniffle/pull/1162#discussion_r1300808432_

**Comment by pegasas** [comment]
Hi, @jerqi , 

I will make a PR for this to go through shuffle server logic for learning.
Would you please assign me this issue?
