### ISSUE TITLE
[Improvement] Netty Support getLocalShuffleData and getMemoryShuffleData.

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#1188]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

At present, only sendShuffleData uses netty. The three interfaces getLocalShuffleData, getMemoryShuffleData, and getLocalShuffleIndex all support netty, but they have not been enabled yet.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
any update on this?

**Comment by rickyma** [comment]
I think we already support this. Closed.
