### ISSUE TITLE
[Improvement] ShuffleServer add Direct Memory Metric for monitor

### ISSUE THREAD

**Issue by lifeSo** [apache/incubator-uniffle#1189]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add metric to monit Direct Memory。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
Can this metric, `jvm_buffer_pool_used_bytes{pool="direct"}`, be used to monitor direct memory?

**Comment by zuston** [comment]
Merged #1363

**Comment by lifeSo** [comment]
> Can this metric, `jvm_buffer_pool_used_bytes{pool="direct"}`, be used to monitor direct memory?

https://github.com/apache/incubator-uniffle/pull/1363#discussion_r1423348080

**Comment by lifeSo** [comment]
> Can this metric, `jvm_buffer_pool_used_bytes{pool="direct"}`, be used to monitor direct memory?

@xumanbu

We found "jvm_memory_bytes_used nonheap" is not correct, and it is small than direct memory.
When OutOfDirectMemory is throw，"jvm_memory_bytes_used nonheap" is small and not correct.


![image](https://github.com/apache/incubator-uniffle/assets/9440617/788a4269-89f3-4395-a9e0-3a24af7e2eba)

![image](https://github.com/apache/incubator-uniffle/assets/9440617/e18de3ab-00ce-4f5c-9234-061b87ecf7d3)
