### ISSUE TITLE
[Improvement] Support configurable for storing shuffle data to a secured HDFS cluster by a spark job user

### ISSUE THREAD

**Issue by xumanbu** [apache/incubator-uniffle#1192]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Storing shuffle data to secured HDFS cluster by spark job user's at now. 
but if we use split kerberos user by component, uniffle will have a independent user, all shuffle data will storing by uniffle user.

therefore, I suggest the user for storing shuffle data is configurable, getting user from ugi in client or get user in spark config.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
@jerqi  @zuston

**Comment by jerqi** [comment]
> @jerqi @zuston

Make sense,  could you raise a pr?

**Comment by xumanbu** [comment]
> > @jerqi @zuston
> 
> Make sense, could you raise a pr?

ok，I think about how to achieve it better, is the config on the client or on the server. the application user also used in quota check. how do u think?

**Comment by jerqi** [comment]
> > > @jerqi @zuston
> > 
> > 
> > Make sense, could you raise a pr?
> 
> ok，I think about how to achieve it better, is the config on the client or on the server. the application user also used in quota check. how do u think?

I think it's a server's config option.
