### ISSUE TITLE
[Improvement] only invoking LOG.debug when `LOG.isDebugEnabled()` is true

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#1201]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently in part of the code,  `LOG.debug` was invoked without deciding if `LOG.isDebugEnabled()` is true, which will have an impact on performance.

### How should we improve?

Only invoking `LOG.debug` when `LOG.isDebugEnabled()` is true.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
> /assigne to me ?

Thanks.
