### ISSUE TITLE
[Improvement] Optimize cleanupStorageSelectionCache method in LocalStorageManager.

### ISSUE THREAD

**Issue by zhuyaogai** [apache/incubator-uniffle#1209]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Assuming there are 500 running APPs, each APP has an average of 10 shuffleIds, and each shuffleId has 1000 partitions, then the size of partitionsOfStorage in LocalStorageManager is about 5000000. The cleanupStorageSelectionCache method can take 500ms on average (sometimes it took a longer time when the size of partitionsOfStorage is larger). So it should be optimized.

Also assuming we complete 10,000 APPs in a day, if we use the AppPurgeEvent event to release resources, it would take approximately 10,000 * 500ms = 5000s. But if we use the ShufflePurgeEvent event to release resources, then it would take 10,000 * 500ms * 10 = 50,000s, which is quite crazy.

### How should we improve?

1. Optimize cleanupStorageSelectionCache method in LocalStorageManager.
2. Fix bug when release resource using ShufflePurgeEvent event.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
Good Catch. I find the same problom.
