### ISSUE TITLE
[Bug] Unexpectedly removing resources even though the App has re-registered shuffle later.

### ISSUE THREAD

**Issue by zhuyaogai** [apache/incubator-uniffle#1211]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Suppose in such a scenario, App is expired due to no heartbeat, so it was added to expired queue and will be removed resources soon. Also At this moment, this app re-registers shuffle. But after re-registering shuffle, the app was removed resources. The following requireBuffer will appear NO_REGISTERED...

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Once the app is marked as unregistered, I think it's acceptable to reject. WDYT? @zhuyaogai

**Comment by zhuyaogai** [comment]
@zuston hi, I don't think so. Let's assume this scenario, there are multi stages(DAGs) in an application. If stage1 requires `ShuffleServer1`, but stage2 does not require `ShuffleServer1`, so the resources of `ShuffleServer1` will be released after stage1 ends. Due to no heartbeat, `ShuffleServer1` will add the application to the expired queue and wait for the resources to be released, but `ShuffleServer1` was required again in stage3, then some unexpected problems will occur. But we know that the application is still in progress.

**Comment by zuston** [comment]
The heartbeat of app with one shuffle-server also will happen in spark driver side.

**Comment by zhuyaogai** [comment]
@zuston If we remove resources after per stage, we use `ShuffleWriteClientImpl#unregisterShuffle` method which will finally remove related shuffle server. 
https://github.com/apache/incubator-uniffle/blob/b4adaa50b7474330ed7723bba3976e090b8bd022/client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java#L994
So there is no heartbeat anymore.

**Comment by zuston** [comment]
> @zuston If we remove resources after per stage, we use `ShuffleWriteClientImpl#unregisterShuffle` method which will finally remove related shuffle servers.
> 
> https://github.com/apache/incubator-uniffle/blob/b4adaa50b7474330ed7723bba3976e090b8bd022/client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java#L994
> 
> 
> So there is no heartbeat anymore.

I think this is right, if the operation of unregister is triggered by spark, it means the data will not be used in the future, the removal is right. Feel free to tell me if I'm wrong.

**Comment by zhuyaogai** [comment]
> @zuston hi, I don't think so. Let's assume this scenario, there are multi stages(DAGs) in an application. If stage1 requires `ShuffleServer1`, but stage2 does not require `ShuffleServer1`, so the resources of `ShuffleServer1` will be released after stage1 ends. Due to no heartbeat, `ShuffleServer1` will add the application to the expired queue and wait for the resources to be released, but `ShuffleServer1` was required again in stage3, then some unexpected problems will occur. But we know that the application is still in progress.

Let's assume this scenario, there are multi DAGs in a tez application(DAG is executed serially one after another). If DAG1 requires `ShuffleServer1`, but DAG2 does not require `ShuffleServer1`, so the resources of `ShuffleServer1` will be released after DAG1 ends. Due to no heartbeat anymore, `ShuffleServer1` will add the application to the expired queue and wait for the resources to be released, but `ShuffleServer1` was required again in DAG3. We assume the following execution sequence.
1. In DAG2, due to no heartbeat anymore, `ShuffleServer1` will add the application to the expired queue, but we know the `clearResourceThread` thread releases resources serially. If the queue is relatively large, it need to wait for a while.
2. In DAG3, the `ShuffleServer1` is required again which will invoke `ShuffleTaskManager#registerShuffle` method.
3. The `clearResourceThread` thread releases application resources.
4. In DAG3, shuffle client will require buffer by invoking `ShuffleTaskManager#requireBuffer` in `ShuffleServer1`, but it just return `NO_REGISTER` status code...

But we know that the application is still in progress.

**Comment by zuston** [comment]
Thanks for your patient explanation @zhuyaogai 👍，got your point and make sense.
