### ISSUE TITLE
[FEATURE][RUST] Support blockId filter when getting data from memory

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1213]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support blockId filter when getting data from memory, this will improve the performance for Spark AQE

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wenlongbrother** [comment]
Hi @zuston I am interested in this task, can you assign it to me?
