### ISSUE TITLE
[Flaky Test] SparkSQLTest and  RepartitionTest

### ISSUE THREAD

**Issue by summaryzb** [apache/incubator-uniffle#1243]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

1.Test class extends `SparkSQLTest` or  `RepartitionTest`
2.Call `IntegrationTestBase`#getShuffleServerConf()
3.Run with wildcard pattern to a specific one test
If above requirements are meet then NullPointerException occurs
Example1: mvn -B   package -Dtest=org.apache.uniffle.test.RepartitionWithLocalFileRssTest -Pspark3.5
```
[INFO] Running org.apache.uniffle.test.RepartitionWithLocalFileRssTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.374 s <<< FAILURE! - in org.apache.uniffle.test.RepartitionWithLocalFileRssTest
[ERROR] org.apache.uniffle.test.RepartitionWithLocalFileRssTest  Time elapsed: 4.373 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.uniffle.test.IntegrationTestBase.getShuffleServerConf(IntegrationTestBase.java:115)
	at org.apache.uniffle.test.RepartitionWithLocalFileRssTest.setupServers(RepartitionWithLocalFileRssTest.java:49)
```

Example2: mvn -B   package -Dtest=org.apache.uniffle.test.SparkSQLWithDelegationShuffleManagerTest -Pspark3.5
```
[INFO] Running org.apache.uniffle.test.SparkSQLWithDelegationShuffleManagerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.021 s <<< FAILURE! - in org.apache.uniffle.test.SparkSQLWithDelegationShuffleManagerTest
[ERROR] org.apache.uniffle.test.SparkSQLWithDelegationShuffleManagerTest  Time elapsed: 4.02 s  <<< ERROR!
java.lang.NullPointerException
  at org.apache.uniffle.test.IntegrationTestBase.getShuffleServerConf(IntegrationTestBase.java:115)
  at org.apache.uniffle.test.SparkSQLWithDelegationShuffleManagerTest.setupServers(SparkSQLWithDelegationShuffleManagerTest.java:59)
```

### Actions URL

No. actions link. This happens when running  specific only one test

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
Merged, thanks @summaryzb.
