### ISSUE TITLE
[FEATURE] [MR] Support to spill large amounts of shuffle data.

### ISSUE THREAD

**Issue by zhengchenyu** [apache/incubator-uniffle#1249]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

https://github.com/apache/incubator-uniffle/commit/8683254720974c7254f9c5c2fd902743ae0ab273 disable write data to MR's OnDiskMapOutput. So it means we can not support the large shuffle data which is over mapreduce.reduce.shuffle.memory.limit.percent * memoryLimit.

In this issue, will enable this function.
Here's the key point:
RssFetcher will fetch compressed data(compressed by uiffle), then decompressed to the parameter 'buffer'. 
But when MergeManagerImpl merge the temporary shuffle data, will use hadoop compression code.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zhengchenyu** [comment]
<img width="601" alt="image" src="https://github.com/apache/incubator-uniffle/assets/10381583/caa17b0c-a2b4-4720-8171-9542e30b1fba">


Upper picture show the data format change. In brief, we have three data format:
Format B: the raw format. It is a sequence of keylen, valuelen, key, value, ending with two -1.
Format A: Format b is compressed according to uniffle encoding.
Format C: Add checksum to format b (IFile format) and compress it according to hadoop encoding.

> The yellow is component of Map. Blue is shuffle server. Green is component of Reduce.

What's the key of the promblem which is described by 8683254720974c7254f9c5c2fd902743ae0ab273?
We write the format B to OnDiskMapOutput, so MergeManagerImpl can not parse it.

**Comment by jerqi** [comment]
Maybe we won't the similar situation. According the logic of data send, we won't produce too large data.

**Comment by zhengchenyu** [comment]
> Maybe we won't the similar situation. According the logic of data send, we won't produce too large data.

Emm. If we use default parameter, won't produce large data. If we increase read buffer size, maybe produce the large shuffle.

And In my test, I decrease mapreduce.reduce.shuffle.memory.limit.percent, then produce this.

If you think so, I will close https://github.com/apache/incubator-uniffle/pull/1263. But It's better to set some limits that read buffer will never be over than single memory limit.

**Comment by jerqi** [comment]
> > Maybe we won't the similar situation. According the logic of data send, we won't produce too large data.
> 
> Emm. If we use default parameter, won't produce large data. If we increase read buffer size, maybe produce the large shuffle.
> 
> And In my test, I decrease mapreduce.reduce.shuffle.memory.limit.percent, then produce this.
> 
> If you think so, I will close #1263. But It's better to set some limits that read buffer will never be over than single memory limit.

It's ok for you to raise a pr. I just state the reason why we don't support this feature at first.

**Comment by zhengchenyu** [comment]
This process mainly occurs during the fetch block. If the number of bytes obtained exceeds the threshold (the default is 0.25 bytes of reduce memory), the data will be stored directly on the disk. In fact, we can precisely control the size of readbuffersize, the default is 14M. We should avoid this process through parameters, rather than support this process. What's more, if the readbuffersize is not adjusted large enough, this process will not happen. So close this PR.
