### ISSUE TITLE
[Improvement] optimize collections contruction

### ISSUE THREAD

**Issue by summaryzb** [apache/incubator-uniffle#1256]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1. Some empty collections are only for read, so replace it with `Collections.emptyList()`, `Collections.emptySet()`, `Collections.emptyMap()`.
2. Set a properly initial size
3. In spark, writer client construct a new List prepared for `shuffleBlockInfos` per record, But in most case there is no blocks produced.

improve above scenarios

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
Fixed by https://github.com/apache/incubator-uniffle/pull/1257
