### ISSUE TITLE
[Improvement] Add timeout reconnection in DelegationRssShuffleManager

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#127]
When `DelegationRssShuffleManager` send an `AccessClusterRequest` to the Coordinator, should we increase the logic of overtime resending?

**Comment by jerqi** [comment]
> 

Why do we need this? What's your situation?

**Comment by smallzhongfeng** [comment]
The reason is that the `ShuffleServer` returns the heartbeat at a frequency of 10s each time. The `Coordinator` filters the `ShuffleServer` whose available memory is lower than the threshold value, which may cause the `ShuffleServer` to be lower than the allocable quantity. In this way, it is pushed down to SSM, add a retry logic and two parameters, retry times and time. Within the user's expected retry time, run on RSS as much as possible.WDYT?

**Comment by jerqi** [comment]
Similar pr: https://github.com/apache/incubator-uniffle/pull/115 , Could it solve your issue?

**Comment by jerqi** [comment]
> Similar pr: #115 , Could it solve your issue?

My fault. I misunderstand you. The improvement is acceptable for me. Do you want to raise a pr?

**Comment by smallzhongfeng** [comment]
Sure, I am trying to do this.

**Comment by jerqi** [comment]
Solved by #139
