### ISSUE TITLE
[Bug] client memory leak with netty #1355

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1359]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

![image](https://github.com/apache/incubator-uniffle/assets/8609142/9c277a79-0f48-4fa0-ba65-84c335fd48c4)

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
I've encountered this problem too. Any ideas to fix this? @zuston

**Comment by zuston** [comment]
> I've encountered this problem too. Any ideas to fix this? @zuston

I don't reproduce this case, do you want to fix this? @rickyma

**Comment by rickyma** [comment]
I can reproduce this issue when we are doing stress testing, but I don't know how to fix it. It seems to be a problem with the underlying code handling in Netty. @zuston

**Comment by rickyma** [comment]
I think we can close this now. @zuston

**Comment by rickyma** [comment]
@jerqi @zuston We can close this.

**Comment by zuston** [comment]
> @jerqi @zuston We can close this.

Is everything ok ?

**Comment by rickyma** [comment]
> > @jerqi @zuston We can close this.
> 
> Is everything ok ?

Yes.

**Comment by zuston** [comment]
> > > @jerqi @zuston We can close this.
> > 
> > 
> > Is everything ok ?
> 
> Yes.

thanks for your effort
