### ISSUE TITLE
[Improvement][Aqe] Avoid calling `getShuffleResult` multiple times

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#136]
When we use AQE, we may call `shuffleWriteClient.getShuffleResult` multiple times. But if both partition 1 and partition 2 are on the server A, we call getShuffleResult(partition 1) to get data form server A, and then we call getShuffleResult(partition 2) to get data form server A, it's not necassray. We can get getShuffleResult(partition 1, partition 2) instead.

**Comment by leixm** [comment]
Maybe I can take this ticket, could you assign this to me? @jerqi

**Comment by jerqi** [comment]
Thanks, you're welcome.

**Comment by jerqi** [comment]
resolved by #190
