### ISSUE TITLE
[FEATURE] support shuffle partition data write to multiple shuffle servers

### ISSUE THREAD

**Issue by xumanbu** [apache/incubator-uniffle#1373]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently, data from one partition can only be written to a designated shuffle server. 

In some scenarios, such as when a large partition occupies a significant amount of shuffle server disk space, this can lead to server crashes in extreme cases.

Based on #825, we could support writing one partition data to multiple shuffle servers.

### Motivation

https://docs.google.com/document/d/1FRGP82R7JBnr3IjmF8PQ6qWP9GnKQsk-N1OWk_f1kSY

### Describe the solution

![shuffleServer drawio](https://github.com/apache/incubator-uniffle/assets/9135743/b34f208c-3005-4da9-9990-e19afbbb2d08)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
When to trigger the next node write?

Two strategies I propose are:
- Based on the application quota of a shuffle server.
- Based on the shuffle server's health status.

@jerqi @zuston @leixm

**Comment by zuston** [comment]
+1 for that.

I hope the trigger strategies could be designed as the pluggable mechansim

**Comment by connorlwilkes** [comment]
How would this differ from `rss.data.replica.write`

**Comment by jerqi** [comment]
> When to trigger the next node write?
> 
> Two strategies I propose are:
> 
> * Based on the application quota of a shuffle server.
> * Based on the shuffle server's health status.
> 
> @jerqi @zuston @leixm

+1 for this proposal.

**Comment by jerqi** [comment]
> How would this differ from `rss.data.replica.write`

This may only write one replica but the replica can be stored in different servers.

**Comment by xumanbu** [comment]
@jerqi @zuston added a dataflow diagram in ***describe the solution*** for implementation plan.

**Comment by zuston** [comment]
> @jerqi @zuston added a dataflow diagram in _**describe the solution**_ for implementation plan.

Looks good.

**Comment by jerqi** [comment]
> @jerqi @zuston added a dataflow diagram in _**describe the solution**_ for implementation plan.

You would better give us a google document.

**Comment by xumanbu** [comment]
> > @jerqi @zuston added a dataflow diagram in _**describe the solution**_ for implementation plan.
> 
> You would better give us a google document like https://docs.google.com/document/d/1p1PksBN2LJ-OtGEHvdyEuH9b1Mv1aD_exMPl4TNaTs0/edit#heading=h.c7fauf9cicbi

OK. added a google doc https://docs.google.com/document/d/1FRGP82R7JBnr3IjmF8PQ6qWP9GnKQsk-N1OWk_f1kSY

**Comment by zuston** [comment]
LGTM. Please go ahead.

**Comment by maobaolong** [comment]
@xumanbu This is a great feature! But it seems not finished. I guess it lack a piece about how server reject the ` large partition` and split to write to another server. WDYT?

**Comment by maobaolong** [comment]
@xumanbu Thanks for your reply, I submit a PR https://github.com/apache/incubator-uniffle/pull/2093/files  to support write shuffle data to multiple shuffle servers, PTAL.
