### ISSUE TITLE
[Bug] Direct memory may leak in exceptional scenarios in shuffle server.

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1391]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

code: https://github.com/apache/incubator-uniffle/pull/1357/files#diff-8ce1686a7767273a5dcf2f8520a9d7767582e7b3f21d8c12056a45d874b7bf44R151

According to [#1357](https://github.com/apache/incubator-uniffle/pull/1357), if the first for loop execution fails, the first `spd` in the list will not be released, which may cause memory leaks.

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Done by #1392
