### ISSUE TITLE
[Umbrella] Enhance dashboard capabilities.

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#1401]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

You can configure one dashboard to manage multiple clusters, and add dashboard management functions for Coordinators and ShuffleServer.Reference documents for specific functions:
https://docs.google.com/document/d/1pR-pTn3aIZHpKSYDmFVdTijDwaT7INFVXJd5VG0WVpg/edit

### Task list

- Added the ability for the dashboard to connect to multiple coordinators and shuffle servers.
- Add sorting and search functions to the dashboard list area for ease of use.
- Added the dashboard account password login function.
- Dashboard added functions for adding and deleting ShuffleServer nodes offline and blacklist.
- Added monitoring status indicators of the ShuffleServer node.
- https://github.com/apache/incubator-uniffle/issues/1618
- https://github.com/apache/incubator-uniffle/issues/1622
- https://github.com/apache/incubator-uniffle/issues/1623
- https://github.com/apache/incubator-uniffle/issues/1624
- https://github.com/apache/incubator-uniffle/issues/1688

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yl09099** [comment]
@zuston @jerqi @lifeSo Let's see if these functions make sense.

**Comment by lifeSo** [comment]
> @zuston @jerqi @lifeSo Let's see if these functions make sense.

OK, I am new to dashboard, let's me see seee first and will try.

**Comment by rickyma** [comment]
Is the current dashboard functioning correctly? I see many 404 error requests on the shuffle server page. 
![image](https://github.com/apache/incubator-uniffle/assets/13834479/18c8a4a9-2d87-4b9c-a1c4-0711f84a6c31)
@yl09099 @lifeSo @jerqi

**Comment by yl09099** [comment]
> Is the current dashboard functioning correctly? I see many 404 error requests on all dashboard pages. ![image](https://private-user-images.githubusercontent.com/13834479/293407204-18c8a4a9-2d87-4b9c-a1c4-0711f84a6c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjE0MzUsIm5iZiI6MTcwNDE2MTEzNSwicGF0aCI6Ii8xMzgzNDQ3OS8yOTM0MDcyMDQtMThjOGE0YTktMmQ4Ny00YjljLWExYzQtMDcxMWY4NGE2YzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAyMDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NjdkNjRiMjZhMGQxNTMwZDNjZGFlZDNjMzExNmUyYjhiNGY3ZjVkYWNiNjc5OTgyMmYzY2JkNTA2YThjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yR3WXkO3Axa39dJ-IHlkXmJieHcLqYDzJhJR-cvhIeE) ![image](https://private-user-images.githubusercontent.com/13834479/293407378-19e98fc7-2fb3-441f-834f-f15be73d0efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjE0MzUsIm5iZiI6MTcwNDE2MTEzNSwicGF0aCI6Ii8xMzgzNDQ3OS8yOTM0MDczNzgtMTllOThmYzctMmZiMy00NDFmLTgzNGYtZjE1YmU3M2QwZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAyMDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMWE0NDE2ZTY3ZDk4ODBmMzc2NGNmNDc1ZDVmZTk4ZWMzZThkMmYxZGVlMjRiYjljZTI0NTQzN2VkOWUxMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJ5OHnoO9miWyy41xO9KLHif_UFZV5-bZuITJFvY_cE) ![image](https://private-user-images.githubusercontent.com/13834479/293407404-475a3172-5976-4b90-8fd9-205f65ebada7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjE0MzUsIm5iZiI6MTcwNDE2MTEzNSwicGF0aCI6Ii8xMzgzNDQ3OS8yOTM0MDc0MDQtNDc1YTMxNzItNTk3Ni00YjkwLThmZDktMjA1ZjY1ZWJhZGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAyMDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDBmZDMzZGExMzFlZTNiNTgyYWU2YzVhNDI5YWJmMGE4MzcyYzc5MWU0MDZhZjU3Y2M1OTFiNGEzNTgwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7EhuJ2PSIfr6Zp06tmHVpy09aKlDIwgoHWweBJz3K0) @yl09099 @lifeSo @jerqi

Is the code up to date?

**Comment by rickyma** [comment]
It's up to date. I don't know why this is happening. Am I missing something? @yl09099

**Comment by yl09099** [comment]
> It's up to date. I don't know why this is happening. Am I missing something? @yl09099

Is the Coordinator interface access address correctly configured? The error is that the interface cannot be accessed，Refer to configuration here：https://github.com/apache/incubator-uniffle/blob/master/docs/dashboard_guide.md.

**Comment by rickyma** [comment]
> > It's up to date. I don't know why this is happening. Am I missing something? @yl09099
> 
> Is the Coordinator interface access address correctly configured? The error is that the interface cannot be accessed，Refer to configuration here：https://github.com/apache/incubator-uniffle/blob/master/docs/dashboard_guide.md.

All we do is update the code to the latest. The config file `dashboard.conf` hasn't been changed at all. @yl09099

**Comment by rickyma** [comment]
So I am just wondering, if the latest code works fine?

**Comment by yl09099** [comment]
> So I am just wondering, if the latest code works fine?

You should have no problem using the latest version of the code.

**Comment by rickyma** [comment]
Can we display `usedDirectMemory` on the Dashboard's shuffle server page? Maybe add a column? If you think there are too many columns and it doesn't look nice, can we remove the first column `Id`? Displaying `Id` on the page doesn't serve any purpose, right? `Id` can be composed of the values in the following columns (IP + GrpcPort + NettyPort).

PTAL @yl09099

**Comment by lifeSo** [comment]
I personly do not think add `usedDirectMemory` is necessary if your company have other monitor system like:

![image](https://github.com/apache/incubator-uniffle/assets/9440617/f8abcacd-eb05-4e0f-8af7-da8bf92962ca)

If I want to see the metric, I will use mtric system.

**Comment by lifeSo** [comment]
Id can be composed of the values in the following columns (IP + GrpcPort + NettyPort).

@yl09099  What do you think ?

**Comment by rickyma** [comment]
![image](https://github.com/apache/incubator-uniffle/assets/13834479/9270431b-d877-43c2-8731-ea60642cda3e)
`usedDirectMemory` has already become a very important metric in the latest Uniffle(especially when enabling Netty). 

I'm just making a suggestion for your reference. Since the `Id` is not very useful anymore(actually useless), you might as well  conveniently replace it with `usedDirectMemory`.

@lifeSo

**Comment by lifeSo** [comment]
It is my  personal opinion， if you persist it. 
I just think dashboard is the place to operate server， and there is monitor system to see metric.
@jerqi   @yl09099  What's your idea?

**Comment by yl09099** [comment]
> Can we display `usedDirectMemory` on the Dashboard's shuffle server page(which is very useful in my opinion)? Maybe add a column? If you think there are too many columns and it doesn't look nice, can we remove the first column `Id`? Displaying `Id` on the page doesn't serve any purpose, right? `Id` can be composed of the values in the following columns (IP + GrpcPort + NettyPort).
> 
> PTAL @yl09099

I don't think it's useful either. We can change it.

**Comment by yl09099** [comment]
> I personly do not think add `usedDirectMemory` is necessary if your company have other monitor system like:
> 
> ![image](https://private-user-images.githubusercontent.com/9440617/296943231-f8abcacd-eb05-4e0f-8af7-da8bf92962ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzI5MzYsIm5iZiI6MTcwNjA3MjYzNiwicGF0aCI6Ii85NDQwNjE3LzI5Njk0MzIzMS1mOGFiY2FjZC1lYjA1LTRlMGYtOGFmNy1kYThiZjkyOTYyY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDUwMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzMzZmNiOGMzZTgyNjFkMDFiMDQyOGE5NDE2MzhhOTI3NzBiZGU4YWUyNWRiMTY1NTA5OTUyYWJmZmQ4NWRhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.85deudrLRsJuTIOoI2E8SDxRMLabaAvE0KGUc22Uo-Q)
> 
> If I want to see the metric, I will use metric system instead of dashboard.

I also do not have what good idea, document change inside, https://docs.google.com/document/d/1pR-pTn3aIZHpKSYDmFVdTijDwaT7INFVXJd5VG0WVpg/edit

**Comment by yl09099** [comment]
> Id can be composed of the values in the following columns (IP + GrpcPort + NettyPort).
> 
> @yl09099 What do you think ?

I think it's useless. We can change it.
