### ISSUE TITLE
[Improvement] Add the number of unhealthy nodes in CoordinatorMetrics

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#146]
When we turn on HealthCheck, shall we add a new metric for unhealthy node. WDYT? @jerqi

**Comment by jerqi** [comment]
Make sense. Do you want to raise a pr?

**Comment by smallzhongfeng** [comment]
Yes, I'm doing now.

**Comment by jerqi** [comment]
solved by #147
