### ISSUE TITLE
[FEATURE] Provide dedicated unregister app rpc interface

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1476]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

```
@Override
  public void unregisterShuffle(String appId) {
    if (appId == null) {
      return;
    }
    Map<Integer, Set<ShuffleServerInfo>> appServerMap = shuffleServerInfoMap.get(appId);
    if (appServerMap == null) {
      return;
    }
    appServerMap.keySet().forEach(shuffleId -> unregisterShuffle(appId, shuffleId));
  }
```

### Motivation

I found the unregister app in shuffleManager stop method always is timeout when having too much stages. And there is no need to unregister shuffle one by one, why not introducing unregister app rpc method? 

But I'm hesitant whether to reuse the unregisterShuffle rpc by making the shuffleId of protobuf optional to achieve the app purging

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
cc @xianjingfeng @jerqi . WDYT? Whether to introduce new rpc or reusing the existing

**Comment by xianjingfeng** [comment]
> cc @xianjingfeng @jerqi . WDYT? Whether to introduce new rpc or reusing the existing

I think it is better to introduce new rpc interface. For compatibility.

**Comment by somelovelanguage** [comment]
Kindly to ask if there is somebody working for this issue？ If not, i'm glad to undertake it.

**Comment by zuston** [comment]
> Kindly to ask if there is somebody working for this issue？ If not, i'm glad to undertake it.

Feel free. Assigned
