### ISSUE TITLE
[DOCS] What does a decomission actually do

### ISSUE THREAD

**Issue by connorlwilkes** [apache/incubator-uniffle#1499]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

It is not currently clear from the documentation what a decommission does. It would be good to have some documentation about that

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
cc @xianjingfeng

**Comment by xianjingfeng** [comment]
@connorlwilkes Please see the design doc. https://docs.google.com/document/d/1p1PksBN2LJ-OtGEHvdyEuH9b1Mv1aD_exMPl4TNaTs0/edit?pli=1

**Comment by zuston** [comment]
Close this. Feel free to reopen if having any problem
