### ISSUE TITLE
[Bug] RssMRUtils.convertTaskAttemptIdToLong produces too large taskAttemptIds

### ISSUE THREAD

**Issue by EnricoMi** [apache/incubator-uniffle#1518]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The `RssMapOutputCollector` creates an RSS task attempt id via `RssMRUtils.convertTaskAttemptIdToLong`:
https://github.com/apache/incubator-uniffle/blob/866f5ff121948e2144729300a0f5cb03510db29d/client-mr/core/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java#L102-L104

that is later used to create an RSS block id:
https://github.com/apache/incubator-uniffle/blob/866f5ff121948e2144729300a0f5cb03510db29d/client-mr/core/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java#L379

However, the RSS task attempt id created by `RssMRUtils.convertTaskAttemptIdToLong` may exceed `Constants.MAX_TASK_ATTEMPT_ID` if `highBytes > 0`:
https://github.com/apache/incubator-uniffle/blob/866f5ff121948e2144729300a0f5cb03510db29d/client-mr/core/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java#L51-L66

I think what this method is trying to do is create an RSS task attempt id where the upper `MAX_ATTEMPT_LENGTH` bits consist of the `taskAttemptID.getId()`, and the lower `TASK_ATTEMPT_ID_MAX_LENGTH - MAX_ATTEMPT_LENGTH` bits of the `taskAttemptID.getTaskID().getId()`.

I am just wondering why this is not breaking:
https://github.com/apache/incubator-uniffle/blob/866f5ff121948e2144729300a0f5cb03510db29d/client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java#L57-L63
in
https://github.com/apache/incubator-uniffle/blob/866f5ff121948e2144729300a0f5cb03510db29d/client/src/main/java/org/apache/uniffle/client/util/ClientUtils.java#L42

That would mean `highBytes` is always `0`.

It looks like the TEZ client has pretty much the same logic, but there it uses `RssTezUtils.getBlockId` to create the RSS block id, which first deconstructs the task attempt id, and therefore does not suffer from this issue.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Done with #1529
