### ISSUE TITLE
[Improvement] [SPARK]Optimize shuffle reading when both sort and combine are used.

### ISSUE THREAD

**Issue by zhengchenyu** [apache/incubator-uniffle#1543]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

See SPARK-46512 for details

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Nice catch, looking forward this!
