### ISSUE TITLE
[Serious Bug] The number of output rows in SortMergeJoin has increased after enabling RSS

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1555]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Updated:
The results when enabling RSS seem to be arbitrary, producing a different outcome each time the SQL is executed. There must be an issue somewhere.

The tpcds SQL used to reproduce the bug:
```
select count(*) from (select * from (select s.*,c.* from (select *,floor(rand()*82857000) as sr from store_sales) s join (select*,floor(rand()*82857000)as cr from customer)  c on s.sr=c.cr) sc DISTRIBUTE BY sc.ss_customer_sk,sc.ss_item_sk)
```

Enable RSS (The result of the SQL is copied from the Spark stdout log):
![image](https://github.com/apache/incubator-uniffle/assets/13834479/f2ea99ee-3c96-4084-b4ec-34349edc844b)
![image](https://github.com/apache/incubator-uniffle/assets/13834479/6c8f0733-7599-4428-a549-26248fbe5761)
![image](https://github.com/apache/incubator-uniffle/assets/13834479/447747bb-7f11-49b7-98cd-9975cc4d1f90)

Disable RSS (The result of the SQL is copied from the Spark stdout log):
![image](https://github.com/apache/incubator-uniffle/assets/13834479/421a8676-e536-4ddc-8f57-7f58d4821a08)
![image](https://github.com/apache/incubator-uniffle/assets/13834479/be557779-c81c-4ef9-80d7-2a57bee561e2)
![image](https://github.com/apache/incubator-uniffle/assets/13834479/3c8ecd07-7195-4654-95be-73e5a8dfa234)

### Affects Version(s)

master

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
I'm not sure whether this will happen on the task failure.

**Comment by rickyma** [comment]
This might not be a bug. I'll close this for now. If I can reproduce this, I will reopen it.

**Comment by EnricoMi** [comment]
Those numbers are collected through Spark accumulators, which are sensitive to rerunning tasks. They over-count the actual number of rows. You should see further down the query plan (the next stage without task failures) the numbers match again.

**Comment by rickyma** [comment]
I have to reopen this. Because I can reproduce this now.

SQL:
```
select count(*) from (select * from (select s.*,c.* from (select *,floor(rand()*82857000) as sr from store_sales) s join (select*,floor(rand()*82857000)as cr from customer)  c on s.sr=c.cr) sc DISTRIBUTE BY sc.ss_customer_sk,sc.ss_item_sk)
```

Enable RSS (The result is copied from spark stdout log):
![image](https://github.com/apache/incubator-uniffle/assets/13834479/f2ea99ee-3c96-4084-b4ec-34349edc844b)

Disable RSS (The result is copied from spark stdout log):
![image](https://github.com/apache/incubator-uniffle/assets/13834479/421a8676-e536-4ddc-8f57-7f58d4821a08)

@zuston @jerqi @EnricoMi PTAL. I think this is a serious bug.

**Comment by EnricoMi** [comment]
Stage 3 (with RSS enabled) has speculative tasks. Their rows count towards the `number of output rows`. Those number are only comparable with `spark.speculation=false` and `spark.task.maxFailures=0`.

**Comment by EnricoMi** [comment]
If you'd do a count in the end you should see differing number of rows with and without RSS if RSS adds rows.

**Comment by rickyma** [comment]
> If you'd do a count in the end you should see differing number of rows with and without RSS if RSS adds rows.

I don't think it's related to Spark speculation, because you can see the final count result is different.

**Comment by EnricoMi** [comment]
The counts are a solid proof.

**Comment by rickyma** [comment]
> The counts are a solid proof.

I totally can't get your point. You think this is not a bug or what do you mean?
I think after enabling RSS, the count results should be the same, right?

I turned speculation off, and you can see the count results are still not the same, the result is different but still larger:
![image](https://github.com/apache/incubator-uniffle/assets/13834479/785b95ce-e78d-4f11-ad7b-05f11bfdf4b0)
![image](https://github.com/apache/incubator-uniffle/assets/13834479/d4b4e866-8300-481f-8e17-7eceffb8b51e)

**Comment by rickyma** [comment]
The issue might be caused by the `rand()` function in my SQL. I will close this issue for now and will reopen it if there are any problems after further confirmation.
