### ISSUE TITLE
[FEATURE] Support Spark 2.1

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1561]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Some companies are still using Spark 2.1, we should support this.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by EnricoMi** [comment]
Spark 2.1 has been EOL'ed almost 6 years ago. Companies are missing out on features, performance and are subject to security issues. This should not be supported. Spark 4.0 will be released this summer.

**Comment by rickyma** [comment]
> Spark 2.1 has been EOL'ed almost 6 years ago. Companies are missing out on features, performance and are subject to security issues. This should not be supported. Spark 4.0 will be released this summer.

For some large companies, upgrading the Spark version is troublesome and complicated, as there are many historical burdens involved. We need to support these users to strengthen the activity of our community, and this will not bring any additional costs or burdens. I will try to implement this part. I think there is no need to worry about it.

**Comment by rickyma** [comment]
@EnricoMi I will close this issue. Spark 2.1 is indeed too old. We only support Spark version 2.4 and above.
