### ISSUE TITLE
[FEATURE] Add metrics about block size distribution, either overall or on a per-application basis.

### ISSUE THREAD

**Issue by leslizhang** [apache/incubator-uniffle#1585]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Add metrics about block size distribution, on overall or on a per-application basis.

### Motivation

We know that in RSS, the size of shuffle blocks generated by Spark tasks can vary greatly due to differences in configurations (such as memory, RDD partition count, etc.). Generally speaking, the larger the shuffle block size generated by a task, the higher the efficiency of transferring shuffle data from the Spark task to the shuffle server. There is also some disk space savings after the shuffle server-side persistence (size of the index file); during shuffle read, the entire index file content is requested in a single read operation. If the index file is too large, the shuffle read process may be negatively affected. By collecting and utilizing the block size distribution, we can assist in optimizing the configuration of Spark jobs, thereby achieving better performance.

### Describe the solution

While caching the shuffle partition data of jobs in the shuffle server, synchronously record the total or per-application block size, and collect it into the histogram type of metrics in Prometheus.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
The PR for this feature will be created only after https://github.com/apache/incubator-uniffle/pull/1574 is merged. Because both PRs modify the same files. @jerqi @zuston

**Comment by rickyma** [comment]
@jerqi @zuston We can close this.
