### ISSUE TITLE
[Bug] Reading local shuffle data in high-pressure scenarios may lead to high system load

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1596]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

1. When enabling Netty, the current timing of releasing `readMemory` in the code is incorrect because the method `client.getChannel().writeAndFlush()` is asynchronous. If we release `readMemory` directly, it will result in `readMemory` being released before it has a chance to take effect. And the file reading only occurs after the `writeAndFlush` method is called. We should add a `ChannelFutureListener` and use its callback mechanism to release `readMemory`. This can ensure the `writeAndFlush` method is truly completed.

2. ~~We haven't set a limit on the maximum number of concurrent requests(for reading local shuffle data) that can be processed at the same time; we only controlled the maximum `readCapacity` of the buffer when reading local shuffle data. This approach falls short. In our tests, we discovered that the metric `read_used_buffer_size` could potentially only reach up to 3.75GB, yet the system load on the shuffle server was already high. This suggests that relying solely on `readCapacity` to manage the reading of local shuffle data is inadequate.~~

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
I will use a thread pool to control the concurrency when reading shuffle data. If anyone has any good suggestions, please feel free to let me know.

**Comment by zuston** [comment]
Read concurrency is not limited in current codebase. +1 for that.

**Comment by jerqi** [comment]
We ever calculated the number of write threads. 2 threads per HDD or  3 threads per SSD will obtain the best performance.
You can evaluate the number threads which we need.

**Comment by dingshun3016** [comment]
Is this error message also affected by this problem? @rickyma 
`24/05/26 12:13:01 WARN [netty-rpc-client-57-5] TransportClient: Failed to send request RPC 1472 to /...:49999: org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 4076863488, max: 4080271360), channel will be closed
`

**Comment by rickyma** [comment]
No, `OutOfDirectMemoryError` should be related to https://github.com/apache/incubator-uniffle/issues/1651.
