### ISSUE TITLE
[Improvement] Use FileChannel to replace FileOutputStream and DataOutputStream in LocalFileWriter

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1613]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

FileChannel can provide better performance than traditional IO streams, as it can take advantage of the underlying operating system's native IO capabilities, such as memory-mapped files and direct buffer access.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
If you have any ideas on this, please let me know.

**Comment by rickyma** [comment]
Close this because FileChannel will cause RSS(Resident Set Size) to grow unexpectedly.

**Comment by maobaolong** [comment]
> Close this because FileChannel will cause RSS(Resident Set Size) to grow unexpectedly.

Hi @rickyma, we just merge the PR to introduce `org.apache.uniffle.storage.handler.impl.LocalFileNioWriter`  last month, so I wonder the context of that issue what you motioned?
