### ISSUE TITLE
[FEATURE] Show Thread Dump in DashBoard

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1618]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

I think it's a good feature to show a coordinator or a shuffle server's thread dump in the dashboard.
It's like you can see an executor's thread dump in Spark UI.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
@yl09099 If you have time. PTAL.

**Comment by yl09099** [comment]
> @yl09099 If you have time. PTAL.

Do you have a good presentation format? suggest.

**Comment by rickyma** [comment]
I think we can refer to the `Executors` tab in Spark UI. Something like(https://spark.apache.org/docs/latest/web-ui.html): 
![image](https://github.com/apache/incubator-uniffle/assets/13834479/3d4a28b2-2160-4c20-990b-63000be6e1da)
![image](https://github.com/apache/incubator-uniffle/assets/13834479/ff32d785-477a-49bf-9efd-9950090a9589)
