### ISSUE TITLE
[DOCS] Add licences and notices regarding new dashboard module

### ISSUE THREAD

**Issue by EnricoMi** [apache/incubator-uniffle#1657]

**Comment by EnricoMi** [comment]
@jerqi what specifically is needed here?
@yl09099 would you like to take this one?

**Comment by jerqi** [comment]
> @jerqi what specifically is needed here? @yl09099 would you like to take this one?

I'm a little busy recently. I will finish the issue after the vocation of Thailand.

**Comment by yl09099** [comment]
> > @jerqi what specifically is needed here? @yl09099 would you like to take this one?
> 
> I'm a little busy recently. I will finish the issue after the vocation of Thailand.

Okay, I'll do it.

**Comment by jerqi** [comment]
There are two kinds of packages for Apache release package: source release package and binary release package.
For different licenses, they will restrict you use them.
 Some license allow you to copy its code to your project, like Apache license. But you shouldn't modify the copied file licenses.
Some licenses don't allow you to copy its code and allow to use the binary package like EPL license.
So Apache project needs to update the dependencies license information in License and License-binary if we add extra dependencies.
