### ISSUE TITLE
[Bug] Incorrect disk size for local storage

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1678]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Currently, the disk size of localStorage's shuffleMeta is not descrease correctly when using appPurgeEvent to remove resources. 
That will make the disk size collected by uniffle leak and then make the disk invalid.

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
When will the disk become invalid? I'm curious that I've never encountered this issue.
