### ISSUE TITLE
[Bug] When a application is expired in one of shuffle servers assigned, all application data on HDFS will be deleted

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#1680]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Currently, when a application is expired in one of shuffle servers assigned, all data of the application on HDFS will be deleted.
And I think this issue is related to #1620

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
@jerqi @zuston @rickyma @dingshun3016 PTAL

**Comment by rickyma** [comment]
Why is this related to https://github.com/apache/incubator-uniffle/issues/1620? You mean you will also encounter "Blocks read inconsistent" issue when fetching shuffle data?

**Comment by xianjingfeng** [comment]
> Why is this related to #1620? You mean you will also encounter "Blocks read inconsistent" issue when fetching shuffle data?

Yes
