### ISSUE TITLE
[Improvement] Introduce the local_storage_is_writable metric

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1682]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Introduce the local_storage_is_writable metric to indicate the local file is writable clearly.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
Is `is_writable` here means `!corrupted`?

**Comment by zuston** [comment]
solved by #1682
