### ISSUE TITLE
[Feature Request] Support push metrics to Prometheus Pushgateway

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#169]
The push mode will be more convenient and more real-time. We have implemented it. If necessary, I will create a PR

**Comment by jerqi** [comment]
Why will the push mode be more convenient and more real-time? Could you give some examples?

**Comment by xianjingfeng** [comment]
1.We need install node exporter in every host, and if not, real-time performance cannot be ensured.
2.We need change the configration of node exporter after we add an instance.

**Comment by xianjingfeng** [comment]
1.We need install node exporter in every host, and if not, real-time performance cannot be ensured.
2.We need change the configration of node exporter after we add an instance.

**Comment by jerqi** [comment]
In our production environment, we use `crontab` to fetch the servers' metrics every minute and push the metrics to our prometheus server. I don't get the difference if we use exporter.

**Comment by xianjingfeng** [comment]
This depends on operation and maintenance. If automation tools is well, it may not be inconvenient.

**Comment by xianjingfeng** [comment]
@jerqi Can you share how do you collect metrics in your k8s cluster?

**Comment by jerqi** [comment]
> @jerqi Can you share how do you collect metrics in your k8s cluster?

We plan to use a k8s sidecar to collect the metrics.

**Comment by xianjingfeng** [comment]
I think we should support export metrics, like hadoop,hbase etc. Users can implement custom export plugin to export metrics to their monitoring system. WDYT? @jerqi

**Comment by jerqi** [comment]
> I think we should support export metrics, like hadoop,hbase etc. Users can implement custom export plugin to export metrics to their monitoring system. WDYT? @jerqi

I'm not familiar with this aspect. If other mature systems have this , I think it will be ok for me. @zuston Do you have some suggestion?

**Comment by zuston** [comment]
The similar mechanism is supported by other systems, like Flink: https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/deployment/metric_reporters/ 

I think this is a good improvement of observability

**Comment by zuston** [comment]
Let's reopen this?

**Comment by jerqi** [comment]
> Let's reopen this?

OK.

**Comment by jerqi** [comment]
Should we have a concept of MetricsReporter refer to Flink first?
