### ISSUE TITLE
[Bug] Asynchronous verification causes invalid resending of data blocks. 

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#1695]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In the checkIfBlocksFailed method, when the failed block list is obtained for the first time, a new failed block is added to the failed block list during the retransmission process. In this case, an exception is thrown and the resend is invalid.

### Affects Version(s)

0.9.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Please look at the master branch code

**Comment by yl09099** [comment]
> Please look at the master branch code
Ok, my question, I read the wrong branch, let me close the issue.

**Comment by yl09099** [comment]
My mistake, straight off.
