### ISSUE TITLE
[Flaky Test] Tests fail because of VM crash

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1698]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project rss-integration-common-test: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common && /usr/lib/jvm/temurin-8-jdk-amd64/jre/bin/java -ea -Xmx3g -jar /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common/target/surefire/surefirebooter7429227444381436354.jar /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common/target/surefire 2024-05-11T16-14-55_901-jvmRun1 surefire6058224363993333182tmp surefire_07324544499115299035tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 1
Error:  Crashed tests:
Error:  org.apache.uniffle.test.FetchClientConfTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common && /usr/lib/jvm/temurin-8-jdk-amd64/jre/bin/java -ea -Xmx3g -jar /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common/target/surefire/surefirebooter7429227444381436354.jar /home/runner/work/incubator-uniffle/incubator-uniffle/integration-test/common/target/surefire 2024-05-11T16-14-55_901-jvmRun1 surefire6058224363993333182tmp surefire_07324544499115299035tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 1
Error:  Crashed tests:
Error:  org.apache.uniffle.test.FetchClientConfTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
Error:  	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:52)
Error:  	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:161)
Error:  	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:73)
Error:  -> [Help 1]

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/9044920297/job/24854106226?pr=1696

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
Maybe we should increase the memory? Current memory is 3g: `<argLine>-ea -Xmx3g</argLine>`.

WDYT? @zuston @jerqi

**Comment by rickyma** [comment]
ping @zuston @jerqi

**Comment by zuston** [comment]
> Maybe we should increase the memory? Current memory is 3g: `<argLine>-ea -Xmx3g</argLine>`.
> 
> WDYT? @zuston @jerqi

Ok for me. We can take a try
