### ISSUE TITLE
[FEATURE] support use skip list to store shuffleBuffer in memory

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#1708]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently, we use linkedList to store shuffleBuffer in memory.  If we assign a lot of memory(1TB) to the shuffle server, the performance will not be good while getting data from memory. Because every request needs to look for `lastBlockId` from the head position.

Other benefits of using skip list:
1. Fix #926
2. We don't need to sort data while flushing data to disk. #137

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
We need to guarantee the order of data, otherwise we will lose the data.

**Comment by xianjingfeng** [comment]
> We need to guarantee the order of data, otherwise we will lose the data.

Get it. This feature will not support `slow start`. I'm going to make it an optional feature.
