### ISSUE TITLE
[Improvement] ShuffleBufferManager supports triggering flush according to the size of single ShuffleBuffer

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#173]
Should shuffleBufferManager supports triggering flush according to the size of single ShuffleBuffer? so that we can make more full use of disk io without waiting for the buffer to reach _`rss.server.buffer.capacity * rss.server.memory.shuffle.highWaterMark.percentage`_

**Comment by leixm** [comment]
I think it's necessary feature, what do u think? @jerqi

**Comment by jerqi** [comment]
> I think it's necessary feature, what do u think? @jerqi

Agree, Do you want to raise a pr?

**Comment by leixm** [comment]
yes, I will create a PR
