### ISSUE TITLE
[Remote Merge] Support different computing frameworks

### ISSUE THREAD

**Issue by zhengchenyu** [apache/incubator-uniffle#1750]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

Support different computing frameworks, including MR, TEZ, SPARK.

### Parent issue

https://github.com/apache/incubator-uniffle/issues/1239

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Is this possible to port this in the rust based shuffle-server? I'm interested on this feature. @zhengchenyu
