### ISSUE TITLE
[Bug] Task that encounters inconsistent data records number fast fail

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1755]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When using the latest master branch code into production env, I found some tasks failed due to the consistent record number. 

After digging this,  I think this is caused by the #1670

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zhengchenyu** [comment]
@zuston Can you please add a new PR to branch-0.9? I think it is a critical fix. But can not cherry-pick to branch-0.9.

**Comment by zhengchenyu** [comment]
#1670 is not merged to branch-0.9, remove this from 0.9.1 milestone.
