### ISSUE TITLE
[Feature] A better strategy to select remoteStoragePath

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#186]
At present, if we configure multiple HDFS paths, the selected strategy is based on the number of apps, which is relatively simple. My idea is to compare the results based on the ratio of all file sizes under the `remoteStoragePath` and the remaining space under the namespace corresponding to the `remoteStoragePath`.

**Comment by smallzhongfeng** [comment]
WDYT? @jerqi

**Comment by jerqi** [comment]
There are many things to consider about HDFS allocation. 
First, the scale of HDFS cluster. There are more DataNodes, the cluster can provide more IO capability.
Second, the remaining space of HDFS cluster. If a shuffle will use too much space, we should give it a enough HDFS cluster, but we should notice that shuffle is a temporary data, we will delete them after we use them. Shuffle data usually don't require too much space like input data and output data.
Third, if you choose to use HDFS with other users, we also need to care the stability of HDFS cluster. If HDFS cluster have two many retries, we should allocate less application to it.
Fourth, we can't forecast how big the shuffle is when we allocate HDFS cluster to it. So we only assume that the one shuffle with big shuffle is the same as the one with small shuffle, it's absolutely wrong in the production cluster. But I don't have any ideas about it.
Finally, it's ok for me to add a new strategy. But we should separate the mechanism from strategy and have some data in production environment to improve the effectiveness of the strategy.

**Comment by smallzhongfeng** [comment]
Thank you for your detailed explanation. I have no doubt about the first two points, but the third point is that I want to know what you mean by the retry of HDFS cluster. And the fourth point is that we really have no way to know the amount of shuffle data, so the current idea is that if there are no files at the beginning, we can only compare the remaining capacity of the namespace. If there are already shuffle files, Then we can compare the ratio of the size of all the shuffle files and the remaining capacity of the namespace under different HDFS paths.

**Comment by jerqi** [comment]
> Thank you for your detailed explanation. I have no doubt about the first two points, but the third point is that I want to know what you mean by the retry of HDFS cluster. And the fourth point is that we really have no way to know the amount of shuffle data, so the current idea is that if there are no files at the beginning, we can only compare the remaining capacity of the namespace. If there are already shuffle files, Then we can compare the ratio of the size of all the shuffle files and the remaining capacity of the namespace under different HDFS paths.

Third point, sorry... I should give more explanation. If shuffle server fail to  write data to HDFS because HDFS high load, shuffle will retry. If there are many retries about HDFS, it means that HDFS have bad status, we should avoid using it.
Fourth, your solution is  not a perfect solution, it must depend data in the production environment  to prove the  effectiveness.

**Comment by smallzhongfeng** [comment]
Yes, we will verify it in the production environment. And thank you again for your advice.

**Comment by jerqi** [comment]
resolved by #192
