### ISSUE TITLE
[Improvement] reject all requests from unregistered apps in shuffle server

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#1887]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently. If a server is restarted, it can still receive requests from clients before the restart. And these requests will waste some computing resources.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
This is useful. When will this be ready to be reviewed?

**Comment by xianjingfeng** [comment]
> This is useful. When will this be ready to be reviewed?

Plan for next week.
