### ISSUE TITLE
[Feature] Support zstd compression

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#189]
### Motivation
ZSTD has a good tradeoff between compression ratio and de/compress speed. For reducing the shuffle-data stored size, it's necessary to support this compression algorithm.

### How to do
1. Introduce the abstract interface of de/compress method
2. Support zstd

**Comment by jerqi** [comment]
Good idea.

**Comment by jerqi** [comment]
You can raise some other issues for other compression codec , such as snappy, as good first issues. Let more people can join our community more easily.

**Comment by jerqi** [comment]
close by #254
