### ISSUE TITLE
[Bug] Incompatibility issues might happen after upgrading the npm version

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1890]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In https://github.com/apache/incubator-uniffle/pull/1870, it bumps the npm version from 8.19.4 to 10.7.0, and I found out that it may cause incompatibility issues with some old glibc when compiling the dashboard:
![image](https://github.com/apache/incubator-uniffle/assets/13834479/02bc7191-5e7f-4889-9858-ecba3c3588c1)

```
[INFO] /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/node/node: /lib64/libm.so.6: versi
on `GLIBC_2.27' not found (required by /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/no
de/node)
[INFO] /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/node/node: /lib64/libstdc++.so.6: 
version `GLIBCXX_3.4.20' not found (required by /data/landun/workspace/project-mission-peak/dashboard/src/main/
webapp/node/node)
[INFO] /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/node/node: /lib64/libstdc++.so.6: 
version `CXXABI_1.3.9' not found (required by /data/landun/workspace/project-mission-peak/dashboard/src/main/we
bapp/node/node)
[INFO] /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/node/node: /lib64/libstdc++.so.6: 
version `GLIBCXX_3.4.21' not found (required by /data/landun/workspace/project-mission-peak/dashboard/src/main/
webapp/node/node)
[INFO] /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/node/node: /lib64/libc.so.6: versi
on `GLIBC_2.28' not found (required by /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/no
de/node)
[INFO] /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/node/node: /lib64/libc.so.6: versi
on `GLIBC_2.25' not found (required by /data/landun/workspace/project-mission-peak/dashboard/src/main/webapp/no
de/node)
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
@yl09099 PTAL.

**Comment by rickyma** [comment]
Should we support old versions of glibc? If we don't need to support them, we can close this issue.

@yl09099 @jerqi

**Comment by jerqi** [comment]
> Should we support old versions of glibc? If we don't need to support them, we can close this issue.
> 
> @yl09099 @jerqi

I prefer not unless it is very necessary.

**Comment by yl09099** [comment]
> Should we support old versions of glibc? If we don't need to support them, we can close this issue.
> 
> @yl09099 @jerqi

Really not very necessary, some of the main framework in the 8.19.4 version of the outdated, I forgot to change back when I did it, the local installation of node greater than or equal to v20.15.0 high version, or upgrade Python greater than or equal to 3.9 version can compile the past.

**Comment by rickyma** [comment]
OK, we don't support old versions of them. Closed.
