### ISSUE TITLE
[Improvement] Resolve DISCLAIMER-WIP / 3rd party sources

### ISSUE THREAD

**Issue by EnricoMi** [apache/incubator-uniffle#1900]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

This project has to complete the work to review the 3rd party source used.

Additionally, during 0.9.0 release, [it has been highlighted](https://lists.apache.org/thread/zls8z2f982r2cg6xmcnx7qffb6o36t5f) that there is 3rd party source from AWS EMR and Zuston/Riffle. Is there iaSoftware Grant Agreement for https://github.com/zuston/riffle?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pjfanning** [comment]
@EnricoMi @jerqi I was going to review the 0.9.1 RC but I wanted to check the progress of this task first.

You appear to have a standard DISCLAIMER in your git master branch. Your LICENSE and NOTICE in git master branch have no mention of 3rd party source code.

This issue has no documentation to describe why this is the case. I highlighted potential issues related to AWS EMR and Zuston/Riffle. Can you explain if there are no issues and why that is the case?

**Comment by pjfanning** [comment]
This file looks like it needs to be mentioned in your LICENSE:

https://github.com/apache/incubator-uniffle/blob/0bb64739d084be258ad86f70dcb7ab7e13f8777e/rust/experimental/server/src/readable_size.rs#L15

**Comment by jerqi** [comment]
> This file looks like it needs to be mentioned in your LICENSE:
> 
> https://github.com/apache/incubator-uniffle/blob/0bb64739d084be258ad86f70dcb7ab7e13f8777e/rust/experimental/server/src/readable_size.rs#L15

OK, I will add this.

**Comment by jerqi** [comment]
> @EnricoMi @jerqi I was going to review the 0.9.1 RC but I wanted to check the progress of this task first.
> 
> You appear to have a standard DISCLAIMER in your git master branch. Your LICENSE and NOTICE in git master branch have no mention of 3rd party source code.
> 
> This issue has no documentation to describe why this is the case. I highlighted potential issues related to AWS EMR and Zuston/Riffle. Can you explain if there are no issues and why that is the case?

The code of two repos is contributed by the same author. Do we need extra explanation in the License file?

**Comment by pjfanning** [comment]
> > This file looks like it needs to be mentioned in your LICENSE:
> > https://github.com/apache/incubator-uniffle/blob/0bb64739d084be258ad86f70dcb7ab7e13f8777e/rust/experimental/server/src/readable_size.rs#L15
> 
> OK, I will add this.

This may be the the only item that needs to be added to your LICENSE. I have https://github.com/apache/incubator-uniffle/issues/2161 open for this. Uniffle has been in Incubation for more than 2 years and as a result, I am not willing to vote on IPMC release votes for Uniffle any more - at least, until you get the LICENSE info correct.
