### ISSUE TITLE
[Bug] Memory may leak when handling SendShuffleDataRequest

### ISSUE THREAD

**Issue by maobaolong** [apache/incubator-uniffle#1917]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Memory may leak when handling SendShuffleDataRequest.
The method `handleSendShuffleDataRequest` return too early before releasing resources (Netty buffers and memory metrics).

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zhengchenyu** [comment]
This issue depends on #1915, but #1915 modified proto. The minor version should not modify the proto, remove this from 0.9.1 milestone.
