### ISSUE TITLE
[Feature] Support spark 3.2.0

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#194]
After SPARK-36892, MapOutputTrackerWorker#getMapSizesByExecutorId has been modified to include method names and return parameter types, Java.lang.NoSuchMethodException will be thrown when the RssShuffleManager#getExpectedTasksByExecutorId method is called, The version of our production environment is 3.2.0.

**Comment by leixm** [comment]
@jerqi  What do you think?

**Comment by leixm** [comment]
Maybe we can support spark 3.2.

**Comment by smallzhongfeng** [comment]
I think it may not be standard to build code by reflection. It may be more appropriate to create different modules and match different versions.

**Comment by jerqi** [comment]
We already supported Spark 3.2.1. You can see the Spark 3.2 profile.

**Comment by jerqi** [comment]
> I think it may not be standard to build code by reflection. It may be more appropriate to create different modules and match different spark versions.

Just avoid too repeated code.

**Comment by leixm** [comment]
> We already supported Spark 3.2.1. You can see the Spark 3.2 profile.

Spark 3.2.1 version re-added the getMapSizesByExecutorId method, but currently uniffle does not support spark 3.2.0, there is a simple way to verify, change the spark.version of the spark 3.2 profile from 3.2.1 to 3.2.0, and then run spark3 integration test can be reproduced

**Comment by jerqi** [comment]
> > We already supported Spark 3.2.1. You can see the Spark 3.2 profile.
> 
> Spark 3.2.1 version re-added the getMapSizesByExecutorId method, but currently uniffle does not support spark 3.2.0, there is a simple way to verify, change the spark.version of the spark 3.2 profile from 3.2.1 to 3.2.0, and then run spark3 integration test can be reproduced

Why not upgrade your spark client version? It's easy to upgrade.

**Comment by leixm** [comment]
> > > We already supported Spark 3.2.1. You can see the Spark 3.2 profile.
> > 
> > 
> > Spark 3.2.1 version re-added the getMapSizesByExecutorId method, but currently uniffle does not support spark 3.2.0, there is a simple way to verify, change the spark.version of the spark 3.2 profile from 3.2.1 to 3.2.0, and then run spark3 integration test can be reproduced
> 
> Why not upgrade your spark client version? It's easy to upgrade.

This is not a problem with the spark client. The exception will be thrown in the Driver process. If we use the current uniffle version, we need to upgrade the spark version of the production environment to 3.2.1.

**Comment by leixm** [comment]
We prefer to support spark3.2.0 in the uniffle client, so the cost will be lower.

**Comment by leixm** [comment]
The main purpose of this issue is to confirm the following two points
1. Uniffle does not support spark3.2.0
2. Should we support spark3.2.0?
Point 1 has been confirmed, I believe that supporting spark 3.2.0 is beneficial to the uniffle community. Some users' production environment is version 3.2.0, but they want to use uniffle to serve their production environment.  We can also give these users a good experience.

**Comment by jerqi** [comment]
If we want to support Spark 3.2.0, should we add a spark3.2.0 profile? The interface is only removed in the Spark 3.2.0 temporarily wrongly. Is it worth to support Spark 3.2.0?

**Comment by leixm** [comment]
What you said is correct, maybe we can provide a patch file for users who need to support spark3.2.0 to apply it themselves, which will neither cause code redundancy nor confuse users. Taking a step back, if we don't support it, we can explain in the documentation that spark3.2.0 is not supported to avoid confusion for users.

**Comment by jerqi** [comment]
It seems not friendly for us to use extra patch. I think we can use reflection in our code to support 3.2.0 and add a profile.Spark 3.2.0 may be a special case, it shouldn't bring too much burden. If we need to maintain every minor version, it really bring too much burden.

**Comment by leixm** [comment]
> I think we can use reflection in our code to support 3.2.0 and add a profile

We can support spark3.2.0 through reflection, but I don't quite understand why profile is needed. Profile cannot control the code logic, it can only be used to control the version of dependencies.

**Comment by jerqi** [comment]
> > I think we can use reflection in our code to support 3.2.0 and add a profile
> 
> We can support spark3.2.0 through reflection, but I don't quite understand why profile is needed. Profile cannot control the code logic, it can only be used to control the version of dependencies.

We need run the test pipeline with the profile to verify that the Spark version is ok and guarantee the new changes won't break the behavior of the version.

**Comment by leixm** [comment]
Maybe I can raise a new pr to add reflection code?

**Comment by jerqi** [comment]
> Maybe I can raise a new pr to add reflection code?

OK.
