### ISSUE TITLE
[Bug] [#1927] The introduction of serverType causes all NPE except GET requests.

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#1954]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

1. #1927 This PR, in addition to the GET request, the rest of the request should report a null pointer exception.
2. Instead of using the OptionsAPI approach, we should use Vue3's CompositionAPI.
3. If the Coordinator URL does not exist, you should not return a random Coordinator URL. Instead, you should return an exception to the front-end.

### Affects Version(s)

0.10.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yl09099** [comment]
@kuszz @maobaolong cc.

**Comment by kuszz** [comment]
> @kuszz @maobaolong cc.

@yl09099 Sorry, I have submit a PR to fix this bug, but I don't understand the describe 2 and 3

**Comment by yl09099** [comment]
> > @kuszz @maobaolong cc.
> 
> @yl09099 Sorry, I have submit a PR to fix this bug, but I don't understand the describe 2 and 3

Let me fix it.
