### ISSUE TITLE
[Bug] The server page of dashboard cannot display server info when refresh the page

### ISSUE THREAD

**Issue by maobaolong** [apache/incubator-uniffle#1985]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

We have to click the other group e.g. decommission nodes and then click active nodes button, the server list can be displayed.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maobaolong** [comment]
@yl09099 Would you like to take a look at this issue?

**Comment by yl09099** [comment]
> @yl09099 Would you like to take a look at this issue?

I'll take care of it. Give it to me.
