### ISSUE TITLE
[Bug] Duplicated blockId cause ShuffleServer memory leak in netty mode.

### ISSUE THREAD

**Issue by lwllvyb** [apache/incubator-uniffle#2105]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Duplicated blockId cause ShuffleServer memory leak in netty mode.

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
Similar issue:#926
