### ISSUE TITLE
[Feature] User's resources quota

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#211]
At present, we can not limit the user's resources. Maybe we can manually update the number of tasks submitted by the user through a configuration file. When the quota is exceeded, the app will be rejected, and the number of apps of different users can be used to represent resource quotas. What do u think? @jerqi

**Comment by zuston** [comment]
Maybe this could be solved by implementing a custom AccessChecker to limit the users quota, I have done this.

**Comment by smallzhongfeng** [comment]
At present, the app level is also limited, right?

**Comment by smallzhongfeng** [comment]
Because I haven't seen similar PR for the time being, so I create this issue.

**Comment by zuston** [comment]
> At present, the app level is also limited, right?

Yes, I introduce a custom access checker to do following operation
1. Do grey-scale.
2. Add the blacklist for some jobs to fallback ESS.
3. ... 

And so I think the resource quotas limitation could be implemented in custom access checker.

Please let me know If I misunderstand u.

**Comment by smallzhongfeng** [comment]
Very coincidentally, our ideas are similar :) .

**Comment by zuston** [comment]
> Very coincidentally, our ideas are similar :) .

Maybe this is the best practice

**Comment by smallzhongfeng** [comment]
When will this feature be available? @zuston

**Comment by zuston** [comment]
I think you misunderstand my thought. I implement the custom access checker to solve the problem you mentioned. You can do similar operations like me. And I think I wont submit this access checker to the uniffle codebase, because maybe it's not  general.

**Comment by smallzhongfeng** [comment]
Well, although I think this may actually have some effect on user isolation, we can try to let users with high priority use more resources. I can understand what you mean.

**Comment by smallzhongfeng** [comment]
In fact, we have also achieved it, and completed the launch, the effect is still obvious, the user's resources are effectively managed, and it is easier to calculate the cost of the user's use for billing, so this issue is mentioned.

**Comment by jerqi** [comment]
User quota is ok for us. I think it's the part work of multi-tent user support.

**Comment by smallzhongfeng** [comment]
I can raise a pr if needed.

**Comment by jerqi** [comment]
> I can raise a pr if needed. @jerqi

If the pr is large, you could write a design document first.

**Comment by Gustfh** [comment]
any update? we also have plan to do this. may i ask whats the scope of the quota limit ? is it on single shuffle server ? or for the whole shuffle size. am thinking maybe we can do it as server level quota, so this feature can work with multiple server feature, the shuffle write could write to rest blocks to another server.

**Comment by zuston** [comment]
Currently I have no ideas on concrete design. If you want to contribute this feature, it’s better to have a simple design doc for reviewing. @Gustfh 

Do u have some plan to invest this ticket? @smallzhongfeng

**Comment by smallzhongfeng** [comment]
In the versions used internally in our company, we use quotas to limit the number of apps that a single user can submit. I don't have much idea about the number of shuffle servers that a single user can use. But I will write a simple document this weekend to discuss whether there are other requirements that can be developed in the future.@jerqi @zuston @Gustfh

**Comment by smallzhongfeng** [comment]
[https://docs.google.com/document/d/1MApSMFQgoS1VAoKbZjomqSRm0iTbSuKG1yvKNlWW65c/edit?usp=sharing](https://docs.google.com/document/d/1MApSMFQgoS1VAoKbZjomqSRm0iTbSuKG1yvKNlWW65c/edit?usp=sharing) If u have time, PTAL @jerqi @zuston

**Comment by smallzhongfeng** [comment]
[https://docs.google.com/document/d/1MApSMFQgoS1VAoKbZjomqSRm0iTbSuKG1yvKNlWW65c/edit?usp=sharing](https://docs.google.com/document/d/1MApSMFQgoS1VAoKbZjomqSRm0iTbSuKG1yvKNlWW65c/edit?usp=sharing) If u have time, PTAL @jerqi @zuston

**Comment by jerqi** [comment]
Could you add some diagrams?

**Comment by smallzhongfeng** [comment]
OK, I will add later.

**Comment by jerqi** [comment]
Could you give us the authority of the `comment`?

**Comment by zuston** [comment]
> Could you give us the authority of the `comment`?

+1

**Comment by smallzhongfeng** [comment]
Sorry, I forgot to give you permission, it has been updated.@jerqi @zuston

**Comment by Gustfh** [comment]
so it's user level quota, what if single app produce large shuffle data, then impact other app, for example a app have large shuffle data and also have lots of stage, and running for days, if you enable memory storage, this app's shuffle could live in memory for long times, am wonder should we have a quota for this situation.

**Comment by zuston** [comment]
> so it's user level quota, what if single app produce large shuffle data, then impact other app, for example a app have large shuffle data and also have lots of stage, and running for days, if you enable memory storage, this app's shuffle could live in memory for long times, am wonder should we have a quota for this situation.

+1. I think the quota of bytes used by app/hadoop-user also should be involved in the design. And I think the different quota limitation like app-number/storage-bytes could be enabled by user.

**Comment by smallzhongfeng** [comment]
> Could you add some diagrams?

I added a simple graphic to illustrate the process of Spark's resource limitation. A more complete pr will be proposed this week.

**Comment by smallzhongfeng** [comment]
> so it's user level quota, what if single app produce large shuffle data, then impact other app, for example a app have large shuffle data and also have lots of stage, and running for days, if you enable memory storage, this app's shuffle could live in memory for long times, am wonder should we have a quota for this situation.

This is a good suggestion. I am currently developing it, which may be implemented in the next pr.

**Comment by smallzhongfeng** [comment]
Of course, I'm looking forward to it.

**Comment by jerqi** [comment]
@Gustfh @smallzhongfeng  I have already send an email https://lists.apache.org/thread/2jlm3fswmsxy619ldyo4px700p3ybnvc. Do you have time at 11 am (UTC +8) Thursday this week?

**Comment by jerqi** [comment]
@smallzhongfeng @Gustfh 

Meeting link is https://meeting.tencent.com/dm/oR95wASCNe91

**Comment by Gustfh** [comment]
ye, we are looking forward to it

**Comment by jerqi** [comment]
Offline Discussion Result:
We should consider the quota of coordinator and the quota of shuffle server .

**Comment by jerqi** [comment]
close by #311
