### ISSUE TITLE
[Improvement] Whether to use jdk cleaner for netty.

### ISSUE THREAD

**Issue by zhengchenyu** [apache/incubator-uniffle#2116]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Initially, under k8s deployment, that is jdk11, I found used_direct_memory_size was always -2.

I found debug log `[main] [DEBUG] PlatformDependent0.<clinit> - direct buffer constructor: unavailable`. It means we will use DirectByteBuffer constructor with cleaner, then means that `Netty will not enforce max memory, and instead will defer to JDK.`

I search the code, found that netty have two ways:

## (1) use jdk cleaner
* Netty will not limit the memory.
* We should use `-XX:MaxDirectMemorySize` to limit DirectByteBuffer. If the limit is reached, GC is triggered.
* We should use metric: `jvm_buffer_pool_used_bytes{pool="direct"}`

## (2) do not use jdk cleaner
* Netty will limit memory with `io.netty.maxDirectMemory`. If the limit is reached, will throw exception.
* We can also use `-XX:MaxDirectMemorySize` to limit DirectByteBuffer, but the usage should be very low. I think there are no need to limit.
* We should use metrics: `used_direct_memory_size`

> BTW, the native memory used in FileOuputStream can not be limited and monitored. We should avoid that.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhengchenyu** [comment]
In my practice, I prefer to not use jdk cleaner. If memory is not enough, we will throw the exception to prompt user. 
But if use jdk cleaner, I found that server will stuck because of full gc can not free the direct memory.

**Comment by jerqi** [comment]
@maobaolong @rickyma

**Comment by zhengchenyu** [comment]
The test shows that (1) and (2) are the same. When the limit is reached, the server will be stuck. Personally think that (1) or (2) it doesn't matter, suggest not to max direct limit, but via `rss.server.buffer.capacity` limit. So end this nonsense.

**Comment by maobaolong** [comment]
@jerqi @zhengchenyu In practice, we set both `MaxDirectMemorySize` and `rss.server.buffer.capacity`, and `MaxDirectMemorySize` is larger than `rss.server.buffer.capacity`.
