### ISSUE TITLE
[Bug] Duplicate blockId causes shuffle Server network to be full.

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#2119]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In Netty mode, if BlockId is duplicated, GetInMemoryShuffleData loops through the same BlockId, causing the single Shuffle Server machine network to be full and the Spark Application to be jammed.
The following is a log of reading the duplicate BlockId：
![image](https://github.com/user-attachments/assets/b89f8da9-cf89-40b2-bdf3-ac744062275e)

### Affects Version(s)

0.10.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yl09099** [comment]
@zuston @jerqi @maobaolong PATL.

**Comment by yl09099** [comment]
@zuston @maobaolong @jerqi @xianjingfeng Have you encountered this problem when using it?

**Comment by yl09099** [comment]
In ShuffleServer,using ShuffleBufferWithLinkedList, Should the ShuffleBufferWithLinkedList class List Change to Set?

**Comment by jerqi** [comment]
> In ShuffleServer,using ShuffleBufferWithLinkedList, Should the ShuffleBufferWithLinkedList class List Change to Set?

BlockId should guanratee not change the order.

**Comment by yl09099** [comment]
> > In ShuffleServer,using ShuffleBufferWithLinkedList, Should the ShuffleBufferWithLinkedList class List Change to Set?
> 
> BlockId should guanratee not change the order.

I can't figure out what caused BlockId to repeat, I thought it was a client timeout at first, but I checked all the logs and there was no timeout.

**Comment by maobaolong** [comment]
@lwllvyb Is it similar with our issue?

**Comment by xianjingfeng** [comment]
> In ShuffleServer,using ShuffleBufferWithLinkedList, Should the ShuffleBufferWithLinkedList class List Change to Set?

You can try `ShuffleBufferWithSkipList`

**Comment by yl09099** [comment]
> > In ShuffleServer,using ShuffleBufferWithLinkedList, Should the ShuffleBufferWithLinkedList class List Change to Set?
> 
> BlockId should guanratee not change the order.

Using LinkedHashSet ensures both de-duplication and order.

**Comment by jerqi** [comment]
> > > In ShuffleServer,using ShuffleBufferWithLinkedList, Should the ShuffleBufferWithLinkedList class List Change to Set?
> > 
> > 
> > BlockId should guanratee not change the order.
> 
> Using LinkedHashSet ensures both de-duplication and order.

Could you paste some more information about this? If it can ensure them, it's ok.

**Comment by yl09099** [comment]
Hash table and linked list implementation of the Set interface, with predictable iteration order. This implementation differs from HashSet in that it maintains a doubly-linked list running through all of its entries. This linked list defines the iteration ordering, which is the order in which elements were inserted into the set (insertion-order). Note that insertion order is not affected if an element is re-inserted into the set. (An element e is reinserted into a set s if s.add(e) is invoked when s.contains(e) would return true immediately prior to the invocation.)
https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashSet.html
