### ISSUE TITLE
[FEATURE] Support refresh page of dashboard

### ISSUE THREAD

**Issue by maobaolong** [apache/incubator-uniffle#2152]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support remember the selected coordinator after refresh page

### Motivation

Now when I refresh the page, the current coordinator will reset to the first one, we want to use one dashboard to show all cluster information, so the list would be many item each one is a coordinator address, when I choose one, and refresh the page, the selected coordinator change to the first one, which is not expected.

### Describe the solution

Using cookies to store the selected address address.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kuszz** [comment]
I will do something for this
