### ISSUE TITLE
[DOCS] Errors in https://uniffle.apache.org/download/

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-uniffle#2295]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

https://uniffle.apache.org/download/ contains several errors

### Affects Version(s)

N/A

### Improving the documentation

Under Apache Uniffle 0.9.0:

https://downloads.apache.org/ncubator/uniffle/0.9.0/apache-uniffle-0.9.0-incubating-src.tar.gz.sha512
should be
https://downloads.apache.org/incubator/uniffle/0.9.0/apache-uniffle-0.9.0-incubating-src.tar.gz.sha512

Under Apache Uniffle 0.7.0:

 https://downloads.apache.org/incubator/uniffle/0.7.1/apache-uniffle-0.7.0-incubating-src.tar.gz.sha512
should be
 https://downloads.apache.org/incubator/uniffle/0.7.0/apache-uniffle-0.7.0-incubating-src.tar.gz.sha512

https://downloads.apache.org/incubator/uniffle/0.7.0/apache-uniffle-0.7.0-incubating-src.tar.gz.asc
should be
https://downloads.apache.org/incubator/uniffle/0.7.1/apache-uniffle-0.7.0-incubating-src.tar.gz.asc

### Anything else

N/A

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
OK, I will correct this. Thanks for you.

**Comment by jerqi** [comment]
I fixed this in the commit https://github.com/apache/incubator-uniffle-website/commit/1fa39292c50b0215074b615f8d2b201dd21fcf21
I will close this issue, thank you again.
