### ISSUE TITLE
[Bug] LICENSE should have PingCap copyright

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-uniffle#2305]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/tikv/raft-engine?tab=readme-ov-file#license includes

Copyright (c) 2017-present, PingCAP, Inc. Released under the Apache 2.0 license. See [LICENSE](https://github.com/tikv/raft-engine/blob/master/LICENSE) for details.

### Affects Version(s)

master & 0.9.2-rc1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Thanks for your advice. But for this rust implementation, I'm considering use another implementaion to replace current code
