### ISSUE TITLE
Flaky test GetShuffleReportForMultiPartTest

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#240]
The test is still flaky 
org.apache.uniffle.test.GetShuffleReportForMultiPartTest
https://github.com/apache/incubator-uniffle/actions/runs/3111709653/jobs/5044305025
@leixm Could you take a look at it?
[test-reports-spark3.zip](https://github.com/apache/incubator-uniffle/files/9632979/test-reports-spark3.zip)

**Comment by leixm** [comment]
I will follow up on this. @jerqi
