### ISSUE TITLE
[FEATURE]  Add a period local storage cleaner thread 

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#282]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Because we don't use strict lock strategy, we will delete some shuffle data normally. If we use strict lock strategy, the performance will be bad. So we want to add  a period local storage cleaner thread.  The thread examine which application is in the disk and judge whether the app exists the memory data structure `ShuffleTaskManager#shuffleTaskInfos`. If memory data structure don't exist, we will delete the data in the disk.

### Motivation

Reduce the garbage data. The data won't be deleted unless the shuffle server is restarted.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sfwang218** [comment]
> @sfwang218 Will you continue this issue? If you need some help, I'm pleased to give you a hand.

Sorry, I'm busy recently, Could you give me some suggestion? I will do it this week.

**Comment by jerqi** [comment]
We can modify the ShuffleTaskManger and LocalStorageManager to implement this function.
For ShuffleTaskManager, you can see  the method `removeResourcesByShuffleIds`, we can refer to it and then add a daemon thread.
For LocalStorageManager, you can add a interface `checkLeakShuffleData(Collection<String> appIds)` for StorageManager. LocalStorageManager implement this interface.

**Comment by sfwang218** [comment]
> We can modify the ShuffleTaskManger and LocalStorageManager to implement this function. For ShuffleTaskManager, you can see the method `removeResourcesByShuffleIds`, we can refer to it and then add a daemon thread. For LocalStorageManager, you can add a interface `checkLeakShuffleData(Collection<String> appIds)` for StorageManager. LocalStorageManager implement this interface.

I think this way does not work, because the appId is a already removed from memory data structure ShuffleTaskManager#shuffleTaskInfos, and we can only parse the appid from the Storage file directory,
and then Compare with ShuffleTaskManager#shuffleTaskInfos.
I'm doing it in this way.

**Comment by jerqi** [comment]
> > We can modify the ShuffleTaskManger and LocalStorageManager to implement this function. For ShuffleTaskManager, you can see the method `removeResourcesByShuffleIds`, we can refer to it and then add a daemon thread. For LocalStorageManager, you can add a interface `checkLeakShuffleData(Collection<String> appIds)` for StorageManager. LocalStorageManager implement this interface.
> 
> I think this way does not work, because the appId is a already removed from memory data structure ShuffleTaskManager#shuffleTaskInfos, and we can only parse the appid from the Storage file directory, and then Compare with ShuffleTaskManager#shuffleTaskInfos. I'm doing it in this way.

Yes, you're right.
You should pass current memory appIds to storageManager by a method `checkLeakShuffleData(Collection<String> appIds)`, storageManager check disks and parse disk appIds. and then storagemanager compare disk appIds and memory appIds. StorageManager remove disk appIds which don't exist in memory appIds.
