### ISSUE TITLE
[FEATURE] Support snappy

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#283]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support snappy to de/compress shuffle-data

### Motivation

The issue of #189 has introduce the abstract interface to support more codecs to match more requirements. This issue is to support snappy.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amaliujia** [comment]
https://github.com/apache/incubator-uniffle/pull/304
