### ISSUE TITLE
[FEATURE]  Make RpcNodePort and HttpNodePort optional

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#290]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Make RpcNodePort and HttpNodePort optional

### Motivation

More flexible

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amaliujia** [comment]
Sending this PR for this issue https://github.com/apache/incubator-uniffle/pull/305
