### ISSUE TITLE
[Bug] Potenial data lost when local storage meets high-watermark 

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#297]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When enable the MEMORY_LOCALFILE storage type in uniffle shuffle-server(it has the 4 disks), the first event of (appId:x,shuffleId:x,partition:1) is flushing from memory to localfile.
But when selecting the storage in `LocalStorageManager`, the disk selected by `localStorages.get(ShuffleStorageUtils.getStorageIndex(localStorages.size(),event.getAppId(),event.getShuffleId(),event.getStartPartition())` is corrupted maybe due to reaching high-watermark (suppose disk0 is corrupted), and so it will fallback to use the disk1.

But the second event of (appId:x,shuffleId:x,partition:1) is flushing, the disk0 has been repaired. It means the second event's data will be flushed to disk0.

And the reading client will fetch the disk0 data directly and ignore data in disk1, that will lost some data for App.

### Affects Version(s)

master

### Additional context

Currently the storage event data flushed is determined by the hash of appId&shuffleId&partitionId and localstorages size, it's a static strategy. That means we should store the state of flushing storages for one partition to solve the corrupted storage problem.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
It's better to introduce dynamic storage selection mechanism to solve this

@jerqi PTAL, I just read the code to find this problem, If I'm wrong, please tell me. Thanks

**Comment by zuston** [comment]
> Maybe we should merge data in disk0 and disk1?

It is OK but firstly we should know the partial data in other storage. Right? This should be considered in detail.

By the way, when reviewing your PR #281 and then surfing this part, I found this bug

**Comment by jerqi** [comment]
How do we determine that disk is broken?
I think the disk can't be read or written. So I don't think this is a bug.
So we should let the application fail fast. But I already have multiple replicas, so it's unnecessary to fail fast.

**Comment by zuston** [comment]
> How do we determine that disk is broken?

I think you are right. The broken disk is marked as corrupted due to the checking of read and write. It wont happen in my above description.

But I think it's necessary to add some test case to keep this logic and I will do this.

**Comment by jerqi** [comment]
close by #298
