### ISSUE TITLE
[Improvement] Make config type of RSS_STORAGE_TYPE as enum

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#299]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Make config type of `RSS_STORAGE_TYPE` in `RssBaseConf` as enum

### How should we improve?

The enum type of config option is introduced in #199, follow this PR to fix the storage type config

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by selectbook** [comment]
is it change to like this?
`public static final ConfigOption<StorageType> RSS_STORAGE_TYPE = ConfigOptions
      .key("rss.storage.type")
      .enumType(StorageType.class)
      .noDefaultValue()
      .withDescription("Data storage for remote shuffle service");`

**Comment by selectbook** [comment]
is it change to something like this?

`public static final ConfigOption<StorageType> RSS_STORAGE_TYPE = ConfigOptions`
    `.key("rss.storage.type")`
    `.enumType(StorageType.class)`
    `.noDefaultValue()`
    `.withDescription("Data storage for remote shuffle service");`

**Comment by jerqi** [comment]
> is it change to something like this?
> 
> public static final ConfigOption RSS_STORAGE_TYPE = ConfigOptions .key("rss.storage.type") .enumType(StorageType.class) .noDefaultValue() .withDescription("Data storage for remote shuffle service");

Yes, do you want to submit a PR?

**Comment by selectbook** [comment]
> > is it change to something like this?
> > public static final ConfigOption RSS_STORAGE_TYPE = ConfigOptions .key("rss.storage.type") .enumType(StorageType.class) .noDefaultValue() .withDescription("Data storage for remote shuffle service");
> 
> Yes, do you want to submit a PR?

yes i will fix this

**Comment by amaliujia** [comment]
I looked this a bit. I thought this requires a good amount of refactoring. For example you might need to move `StorageType.class` to `common` module.
