### ISSUE TITLE
[Improvement] Make config type of RSS_CLIENT_TYPE as enum

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#300]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Make config type of RSS_CLIENT_TYPE as enum

### How should we improve?

The enum type of config option is introduced in https://github.com/apache/incubator-uniffle/pull/199, follow this PR to fix the RSS_CLIENT_TYPE config

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by selectbook** [comment]
Because the change of this issue involves only one class change, I want to use this to verify whether my thinking is correct
