### ISSUE TITLE
[FEATURE] Introduce the general remote fs access layer

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#317]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently, we use the Hadoop filesystem interface to be interactive with S3/OBS/HDFS/COS, maybe this will make uniffle 
bound to Hadoop ecosystem. 

In my opinion, when deploying uniffle into the K8s and directly use the s3 as the backend storage, there is not necessary to use the Hadoop api to visit S3.

So we should introduce the general fs access layer to unify all fs visit, including HDFS/S3, like flink does.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
I have some concern about some low performance operations about object storage such as `Append` operation and `List` operation. Maybe we need extra optimization.

**Comment by zuston** [comment]
This issue may be related with the support of object store. Let's track this in https://github.com/apache/incubator-uniffle/issues/391
