### ISSUE TITLE
[Bug] Log host path access denied when UID is different from GID

### ISSUE THREAD

**Issue by a140262** [apache/incubator-uniffle#323]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

My Spark application's UID is different from GroupID, ie. use `999:1000` to access /data/rssadmin. In the [init container command](https://github.com/apache/incubator-uniffle/blob/e6b4260aa54a9ffda30ec02fa050be1c108e8a9f/deploy/kubernetes/operator/pkg/controller/util/util.go#L214), why do you setup the permission via `GID:GID` instead of the format of `UID:GID` for the host paths? 
The pod securityContext I set is:
```
    securityContext:
      runAsUser: 999
      fsGroup: 1000
```

Both coordinator and server pods threw the permission error:
```
/data/rssadmin/rss/bin/start-coordinator.sh: line 73: /data/rssadmin/rss/logs/coordinator.out: Permission denied
AND
/data/rssadmin/rss/bin/start-shuffle-server.sh: line 96: /data/rssadmin/rss/logs/shuffle_server.out: Permission denied
```

### Affects Version(s)

0.7.0-snapshot

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wangao1236** [comment]
Sorry, this part of the feature does have a bug. Because there are so many arguments in SecurityContext, we initially used fsgroup for convenience and assumed that uid and gid were the same by default. We will fix this as soon as possible, or can you help submit a PR? @a140262

**Comment by wangao1236** [comment]
Sorry, this part of the feature does have a bug. Because there are so many arguments in SecurityContext, we initially used fsgroup for convenience and assumed that uid and gid were the same by default. We will correct this as soon as possible, or we really appreciate that you can help to submit a PR?

**Comment by wangao1236** [comment]
@a140262  have modified it for time reasons, thanks for pointing this out. If possible, we would really appreciate your help in reviewing.
