### ISSUE TITLE
[FEATURE] Expose metrics of TOP10 app bytes in one shuffle server

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#333]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

 It's better to expose metrics of TOP10 app bytes in one shuffle server, especially when reaching the high watermark of disk.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
cc @jerqi @kaijchen Do you have some suggestion on this?

**Comment by jerqi** [comment]
What can the metrics tell us? Which problems do you want to solve?

**Comment by zuston** [comment]
> What can the metrics tell us? Which problems do you want to solve?

When reaching the high watermark, we could kill the max data size  app to keep other apps stability

**Comment by kaijchen** [comment]
I think it's ok to include this metrics if it doen't introduce too much overhead.

**Comment by zuston** [comment]
> I think it's ok to include this metrics if it doen't introduce noticeable overhead.

I think it won’t. The aggregated data of single app used bytes has been collected in current codebase, we just need to expose

**Comment by amaliujia** [comment]
Given this is a starter issue, do you mind sharing some key code pointers to help understand the workflow of the shuffle server that collects then observes the app bytes?

I assume it cannot be limited to only TOP 10 since the metrics will change and there always a need to sort?

**Comment by amaliujia** [comment]
@zuston could you give me some feedback on my WIP PR to see if I am on the right direction: https://github.com/apache/incubator-uniffle/pull/387
