### ISSUE TITLE
[FEATURE] Support Tez Client Design

### ISSUE THREAD

**Issue by bin41215** [apache/incubator-uniffle#337]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

We have made a design about support tez,  details are in this document.
https://docs.google.com/document/d/1__mOXmtqTX5hKFhVjg4VVwT0a7yosFAwO9koGZMHdQg/edit?usp=sharing

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Could you give us the authority of the comment?

**Comment by jerqi** [comment]
Maybe we can reuse https://github.com/apache/incubator-uniffle/issues/321, you can attach the design doc in the issue #321

**Comment by bin41215** [comment]
Sorry, I was working on something else the other day; I just responded to something in the docs.

**Comment by jerqi** [comment]
We will have online meeting to discuss some design details this Thursday at 7:00 pm (UTC +8). If someone have interest, you can tell me.
