### ISSUE TITLE
[FEATURE]  Support rack awareness

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#341]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support rack awareness for better performence.

### Motivation

If our tasks and shuffle servers are not in same rack or same data center,the load of the network switch will be very high, and the performance will be greatly affected. So we need support that the tasks send data to the closest shuffle servers as much as possible.

### Describe the solution

1. Assign rack information to each shuffle server and each compute nodes(such as Yarn Nodemanager/Kubernetes Node). We can store this information to hdfs or other external storage and manage by coordinator.
2. Implement a new `AssignmentStrategy`  that assign nodes in different racks as much as possible.
3. Client get its own rack information from coordinator and send data to the closest shuffle servers as much as possible.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Thanks for proposing this issue. I think it's necessary for the bigger uniffle cluster located in multiple DCs or racks. 

And currently maybe you could use the `tag` to indicate one kind of shuffle-servers but the spark jobs also should be specified the one `tag` . cc @jerqi

**Comment by xianjingfeng** [comment]
> And currently maybe you could use the `tag` to indicate one kind of shuffle-servers

1. I know this feature. For us, it is better to use multiple clusters than tags.
2. Usually, we can't limit all task of one job to run in same rack or same DC.

**Comment by jerqi** [comment]
> 2. Usually, we can't limit all task of one job to run in same rack or same DC.
But all map tasks will send the reduce task to one shuffle server.

**Comment by jerqi** [comment]
Could you give us an example?

**Comment by xianjingfeng** [comment]
> But all map tasks will send the reduce task to one shuffle server

Not always. if we have 3 blocks(1 replicat) and 3 servers and we can send 1 block to each server.

> I can't get your point. Why don't the `tag` solve your problems?

If we have a job with 3 tasks: (task-1: rack-1, task-2: rack-2, task-3: rack-3)
And 3 servers with same `tag`: (server-1: rack-1, server-2: rack-2, server-3: rack-3)
And 3 blocks
task-1 send block-1 to server-2
task-2 send block-2 to server-3
task-3 send block-3 to server-1

**Comment by zuston** [comment]
Emm.. A little tip, the `tag` is bound to job level.

**Comment by jerqi** [comment]
Maybe I got your point. If we have rack1, rack2, rack3. Rack2 may have lower latency than rack3 for rack1. If we have tasks in rack1, rack1 don't have free shuffle server, we should allocate rack2's shuffle server to the tasks. Tag can't be compared. Maybe @xianjingfeng should introduce comparable properties to our scheduler strategy. Do I get your point?

**Comment by xianjingfeng** [comment]
> Maybe I got your point. If we have rack1, rack2, rack3. Rack2 may have lower latency than rack3 for rack1. If we have tasks in rack1, rack1 don't have free shuffle server, we should allocate rack2's shuffle server to the tasks. Tag can't be compared. Maybe @xianjingfeng want to introduce comparable properties to our scheduler strategy. Do I get your point?

I am not sure. 
1.  `AssignmentStrategy` will assign nodes from different racks to a stage.
2.  When task send data to shuffle servers, it will send to the server in the same rack with it first.
3.  When task read data from shuffle servers, it will read from the server in the same rack with it first.

**Comment by jerqi** [comment]
> > Maybe I got your point. If we have rack1, rack2, rack3. Rack2 may have lower latency than rack3 for rack1. If we have tasks in rack1, rack1 don't have free shuffle server, we should allocate rack2's shuffle server to the tasks. Tag can't be compared. Maybe @xianjingfeng want to introduce comparable properties to our scheduler strategy. Do I get your point?
> 
> I am not sure.
> 
> 1. `AssignmentStrategy` will assign nodes from different racks to a stage.
> 2. When task send data to shuffle servers, it will send to the server in the same rack with it first.
> 3. When task read data from shuffle servers, it will read from the server in the same rack with it first.

Is this a feature for multiple replicas?

**Comment by xianjingfeng** [comment]
> Is this a feature for multiple replicas?

Yes

**Comment by jerqi** [comment]
You'd better give us a simple design doc, refer to https://docs.google.com/document/d/1G0cOFVJbYLf2oX1fiadh7zi2M6DlEcjTQTh4kSkb0LA/edit?usp=sharing

**Comment by xianjingfeng** [comment]
Since we used LZ4, our network pressure has going down. And we now support reassign server for one partition. Use single replica seems is a better choice. So support rack awareness is unnecessary.
