### ISSUE TITLE
[Improvement] Shade Netty Native lib

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#343]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Our Netty only shade jar package, never shade netty package, If we use multiple version Netty, our client may be influenced.

### How should we improve?

We can refer to 
https://github.com/apache/spark/pull/24502
https://github.com/apache/incubator-celeborn/pull/908

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cchung100m** [comment]
Hi @jerqi 

Do we still have this issue?  I'd like to work on it if yes.

**Comment by jerqi** [comment]
> Hi @jerqi
> 
> Do we still have this issue? I'd like to work on it if yes.

Yes. You can go ahead.
