### ISSUE TITLE
[Bug][AQE][LocalOrder] Incorrect check of discontinuous blocks  

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#353]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I think we misunderstand the [startMapIndex, endMapIndex). the index is not the map task id, which only indicate the range of the succeed map task ids set. 

So that means. if the range is [0, 5), it only indicate the number of tasks is 5. And the task id list may be as follows:

`[task-1, task-3, task-9, task-15, task-16]`

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
PTAL @jerqi

**Comment by jerqi** [comment]
I have told you this problem. They're related although they're not same. Now we don't have other mechanism to know mapIndex.
