### ISSUE TITLE
[Improvement] Make the coordinator client managed by CoordinatorClientFactory singleton

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#363]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We should make the coordinator client managed by `CoordinatorClientFactory` singleton like the `ShuffleServerClientFactory` does. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cchung100m** [comment]
Hi @zuston 

It's been a while since this issue existed and I'd like to help it if nobody is working on it currently.

**Comment by zuston** [comment]
Feel free to pick up

**Comment by lifeSo** [comment]
How about let's me try and contribute the issue if no body try it.
