### ISSUE TITLE
Flaky Test: WriteAndReadMetricsTest

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#368]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

WriteAndReadMetricsTest

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3561366125/jobs/5986509018

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
This issue duplicates with #409.
Closing this because #409 is more detailed.
