### ISSUE TITLE
Implement rest api for shuffle server and coordinator

### ISSUE THREAD

**Issue by wForget** [apache/incubator-uniffle#37]
We can implement some rest api for the shuffle server and coordinator to get server's status and control server's behavior, and also provide api for the web ui.

**Comment by jerqi** [comment]
There is an activity called Tencent's OpenSourceTalent (https://github.com/Tencent/OpenSourceTalent/issues/28).  The first task is similar to the issue. There will be some students to finish the work.

**Comment by jerqi** [comment]
This issue is duplicated to #80 . I'll close it.
