### ISSUE TITLE
[Bug] Concurrency problems may occur when the ApplicationManager registerApplicationInfo

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#376]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
appAndTime.remove(uuidFromApp);
appAndTime.put(appId, currentTimeMillis);
```
In the process of `registerApplicationInfo` in `ApplicationManager`, we need to remove the uuid and re insert it into the registered appId. This process is not atomic and may cause concurrency problems.
```
int currentAppNum = appAndTimes.size();
if (currentAppNum >= defaultAppNum) {
    ...
}
```
When `AccessQuotaChecker` getting `appAndTimes.size()`, it may be the number of apps before putting appId after removing uuid.

### Affects Version(s)

0.7.0

### Uniffle Server Log Output

[ERROR] 2022-11-29 17:57:39,386 Grpc-199 AccessAppQuotaChecker check - Denied by AccessAppQuotaChecker => User: xxxx, current app num is: 104, default app num is: 80. We will reject this app[uuid=468366284-108712]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Good catch.
