### ISSUE TITLE
[Improvement] Optimize data flushing and memory usage for huge partitions to improve stability 

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#378]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Background 

In our internal uniffle cluster, when using the storage type of `MEMORY_LOCALFILE,` the partial single huge partitions make disk reach high watermark, which make whole shuffle-server out-of-service due to full memory occupation.

### Possible solutions
1. ~~Using the storage type of `MEMORY_LOCALFILE_HDFS` with the fallback strategy of `LocalStorageManagerFallbackStrategy`. #235~~
> ~~After testing this mechanism, I found some bugs which make fallback invalid.~~
2. ~~Introduce the new strategy of dynamic disk selection #373~~
3. ~~Introduce partition size based strategy to flush single huge partition data to HDFS~~

~~Currently, I prefer `3th` solution. In which, we could use cold storage(HDFS) when cumulative size of a particular partition is above a specific threshold(like 50g?). Actually, if exclude the partial huge partitions, the disk free ratio of whole shuffle-server is 20%-30%.~~

#### Reasons
1. ~~We could avoid hotspot of a single shuffle server, which could use HDFS to distribute pressure.~~
2. ~~Especially useful when disk spaces of shuffle servers are limited, which cannot hold a super large shuffle partition.~~
3. ~~Compared with `1th` solution, it is more restrained for HDFS use and will not cause greater pressure. (Actually we don't want to accept much shuffle-data to HDFS with 3 replicas)~~
4. ~~Compared with 2th solution, it is more effective and have better performance.~~
5. ~~Only downgrade storage of partial huge partition jobs to HDFS, which is effective, especially when the HDFS cluster performance is not good.~~

### Final solution
The solution of handling huge partitions is to make it flush to HDFS directly and limit memory usage, all subtasks are as follows.

1. Speed up flushing partition data to HDFS. 
    - [x] #396
2. Introduce the memory usage limitation for huge partitions
    - [x] #458
    - [x] #471 
    - [x] #494 
    - [x] #505 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
After discussing with my mentor, I raise a new proposal. Feel free to discuss more. @xianjingfeng @jerqi

**Comment by jerqi** [comment]
> After discussing with my mentor, I raise a new proposal. Feel free to discuss more. @xianjingfeng @jerqi

What's the advantage of this strategy compared with current strategy?

**Comment by zuston** [comment]
> > After discussing with my mentor, I raise a new proposal. Feel free to discuss more. @xianjingfeng @jerqi
> 
> What's the advantage of this strategy compared with current strategy?

Reasons have been attached.

**Comment by jerqi** [comment]
My concern about this strategy is that we need to maintain more partition meta. Will it give more gc pressure?

**Comment by jerqi** [comment]
> > > After discussing with my mentor, I raise a new proposal. Feel free to discuss more. @xianjingfeng @jerqi
> > 
> > 
> > What's the advantage of this strategy compared with current strategy?
> 
> Reasons have been attached.

Current strategy have picked the most partition to HDFS. You can see our implement.

**Comment by zuston** [comment]
Yes, I have tested this implementation. But it looks invalid when fallback to HDFS. But this is not a big problem.

The key of proposal is to avoid too much data into HDFS, we don't want to accept shuffle data 3 replica in HDFS. And sometimes, the performance is not good.

**Comment by jerqi** [comment]
> Yes, I have tested this implementation. But it looks invalid when fallback to HDFS. But this is not a big problem.
> 
> The key of proposal is to avoid too much data into HDFS, we don't want to accept shuffle data 3 replica in HDFS. And sometimes, the performance is not good.

You can set the data replica with hadoop configuration.

**Comment by zuston** [comment]
This will bring a great burden to the HDFS ops

**Comment by jerqi** [comment]
> This will bring a great burden to the HDFS ops

You misunderstand me. The replica num is a client configuration. We just modify the Spark's client. You can see https://github.com/apache/incubator-uniffle/blob/884921b6d7c5452f6f3548ebc87840071c6be81f/proto/src/main/proto/Rss.proto#L422 for details.

**Comment by jerqi** [comment]
The data which was written to HDFS must be higher than a data size. If we write small data size, it will influence the performance of HDFS.

**Comment by zuston** [comment]
> The data which was written to HDFS must be higher than a data size. If we write small data size, it will influence the performance of HDFS.

I know this, so I hope to use hdfs as little as possible, only open for those huge partition data.

**Comment by jerqi** [comment]
If you write the data which partition size > 50G && event > 64MB, I feel that it's ok.

**Comment by xianjingfeng** [comment]
In our production environment the disk is enough in most of the time. And it is difficult to set the threshold of partition size, and this will result in reduced disk usage. So we prefer to write hdfs when the disk is full.

**Comment by ChengbingLiu** [comment]
@jerqi Here is our scenario:

We co-located Uniffle shuffle servers with our YARN NodeManagers. Therefore the shuffle servers have limited memory (10~20 GB) and limited disk space (1~5 TB). However, there can be as many as 1k shuffle tasks on a shuffle server at the same time, with each task takes up only 1~2MB memory on the average.

When a super large shuffle partition comes in, one of the disks quickly reaches its high watermark and memory starts to flush directly to HDFS. Since each task has only a small size (1~2MB) in the memory, it could flush(append) to HDFS with only 1~2MB at a time even if the configured flush threshold `rss.server.flush.cold.storage.threshold.size` is 64MB.

IMO, the flush threshold works only with two preconditions:
1. The shuffle server has enough memory compared to concurrent shuffle tasks (otherwise the threshold may not be reached)
2. The shuffle server has enough disk space (otherwise small partitions may fallback to cold storage)

If either condition is not met, it's better to have another machanism to better utilize the limited memory/disk resources, instead of wasting them on a uncommonly large partition.

Please correct me if I'm wrong.

**Comment by jerqi** [comment]
> @jerqi Here is our scenario:
> 
> We co-located Uniffle shuffle servers with our YARN NodeManagers. Therefore the shuffle servers have limited memory (10-20 GB) and limited disk space (1-5 TB). However, there can be as many as 1k shuffle tasks on a shuffle server at the same time, with each task takes up only 1~2MB memory on the average.
> 
> When a super large shuffle partition comes in, one of the disks quickly reaches its high watermark and memory starts to flush directly to HDFS. Since each task has only a small size (1-2MB) in the memory, it could flush(append) to HDFS with only 1~2MB at a time even if the configured flush threshold `rss.server.flush.cold.storage.threshold.size` is 64MB.
> 
> IMO, the flush threshold works only with two preconditions:
> 
> 1. The shuffle server has enough memory compared to concurrent shuffle tasks (otherwise the threshold may not be reached)
> 2. The shuffle server has enough disk space (otherwise small partitions may fallback to cold storage)
> 
> If either condition is not met, it's better to have another machanism to better utilize the limited memory/disk resources, instead of wasting them on a uncommonly large partition.
> 
> Please correct me if I'm wrong.

Yes, you're right. But if we only write 2MB to HDFS directly, the HDFS will have poor performance.

**Comment by jerqi** [comment]
Maybe we could introduce multi-thread writing HDFS. If the file is too big, we could split them to multiple files. ByteDance CSS have similar concept. If file exceed the size, we will open and write another file.

**Comment by zuston** [comment]
> Maybe we could introduce multi-thread writing HDFS. If the file is too big, we could split them to multiple files. 

Yes. The key of problem is the low speed of writing single one data file. 

> ByteDance CSS have similar concept. If file exceed the size, we will open and write another file.

Let me take a look. But I think writing another file is not a good solution, which wont improve the writing concurrency for multiple same partition events.

**Comment by jerqi** [comment]
> > Maybe we could introduce multi-thread writing HDFS. If the file is too big, we could split them to multiple files.
> 
> Yes. The key of problem is the low speed of writing single one data file.
> 
> > ByteDance CSS have similar concept. If file exceed the size, we will open and write another file.
> 
> Let me take a look. But I think writing another file is not a good solution, which wont improve the writing concurrency for multiple same partition events.

I mean that we can write multiple files at the same time.
We can tryLock the file lock, we have multiple locks, if we succeed to tryLock, we can write the file. If we fail to tryLock, we will retry another file lock.

**Comment by jerqi** [comment]
> > I mean that we can write multiple files at the same time.
> > We can tryLock the file lock, we have multiple locks, if we succeed to tryLock, we can write the file. If we fail to tryLock, we will retry another file lock.
> 
> Got it. It's an optional solution, the flush speed could improve based on (HDFS speed) * (file number).
> 
> And I think we also need to limit the huge partition app's writing speed to avoid affecting other jobs.

VIP Shop have similarly minds. cc @Gustfh

**Comment by jerqi** [comment]
> > I mean that we can write multiple files at the same time.
> > We can tryLock the file lock, we have multiple locks, if we succeed to tryLock, we can write the file. If we fail to tryLock, we will retry another file lock.
> 
> Got it. It's an optional solution, the flush speed could improve based on (HDFS speed) * (file number).
> 

I feel that it's necessary. Because it will be too slow that the server only use single thread to flush a large partition although we have multiple servers.

**Comment by zuston** [comment]
> I feel that it's necessary. Because it will be too slow that the server only use single thread to flush a large partition although we have multiple servers.

Make sense. I think I will do this optimization.

**Comment by zuston** [comment]
> > I feel that it's necessary. Because it will be too slow that the server only use single thread to flush a large partition although we have multiple servers.
> 
> Make sense. I think I will do this optimization.

Draft a PR #396 .

For this PR, it only solve the problem mentioned  by second case. But if the `ShuffleDataFlushEvent` is so huge(5G) to HDFS, it's still handled by single one thread. So we also need to generate multiple events from huge `ShuffleDataFlushEvent` to improve writing speed when flushing to HDFS.

**Comment by zuston** [comment]
> Introduce the blacklist of a app based on its flushed size, once reached, shuffle-server will let it allow to get limited memory and flush data to HDFS directly

If the huge partition has the high writing speed and the speed of flushing is slow, the most memory will be occupied by huge partition's app. For ensuring the other apps stability, I prefer limiting the memory usage for huge partition. WDYT? @jerqi  cc @advancedxy

**Comment by zuston** [comment]
This issue will track all the optimizations of huge partition, and all sub-tasks will be connected with this. The solution of handling huge partitions is to make it flush to HDFS directly and limit memory usage, all subtasks are as follows.

1. Speed up flushing partition data to HDFS. 
    - [x] https://github.com/apache/incubator-uniffle/pull/396
2. Introduce the memory usage limitation for huge partitions
    - [ ] Record every partition data size in `ShuffleTaskInfo`
    - [ ] Introduce storage selector strategy(to support huge partition flushed to HDFS directly) in MultipleStorageManager to replace fallback strategy
    - [ ] Introduce more metrics to monitor huge partitions and so on
3. Support split huge event into smaller multiple events concurrently to speed up flushing


cc @jerqi @advancedxy I will create some subtasks of issues and PRs, feel free to discuss more.

**Comment by jerqi** [comment]
> This issue will track all the optimizations of huge partition, and all sub-tasks will be connected with this. The solution of handling huge partitions is to make it flush to HDFS directly and limit memory usage, all subtasks are as follows.
> 
> 1. Speed up flushing partition data to HDFS.
>    
>    * [x]  [Support writing multi files of single partition to improve speed in HDFS storage #396](https://github.com/apache/incubator-uniffle/pull/396)
> 2. Introduce the memory usage limitation for huge partitions
>    
>    * [ ]  Record every partition data size in `ShuffleTaskInfo`
>    * [ ]  Introduce storage selector strategy(to support huge partition flushed to HDFS directly) in MultipleStorageManager to replace fallback strategy
>    * [ ]  Introduce more metrics to monitor huge partitions and so on
> 3. Support split huge event into smaller multiple events concurrently to speed up flushing
> 
> cc @jerqi @advancedxy I will create some subtasks of issues and PRs, feel free to discuss more.

It's ok for me.

**Comment by zuston** [comment]
Closed. Feel free to open it if having any problem.
