### ISSUE TITLE
[Bug] Overlook fallback when data-flush event enters into pending queue

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#380]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When using the storage type of `MEMORY_LOCALFILE_HDFS` and enable the fallback strategy of `LocalStorageManagerFallbackStrategy`, it will still fail when one disk reached high watermark.

After digging into the code, I found it is caused by the cache in MultiStorageManager when invoking the selectStorage in the method of `ShuffleFlushManager.processPendingEvents`, that make it lost the chance to use the fallback.

But after removing this cache, I still found it still fail, because this pending event's retries time always=0, so it will make fallback failed. 

So I rethink this pending queue. Do we really need this in multiple storage? I think perhaps not, we could remove this pending queue mechanism when multiple storage manager is enabled. Of course, it's still meaningful for single storage manager.

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
@xianjingfeng I found the fallback strategy is invalid. Could you help check this? CC @jerqi

**Comment by jerqi** [comment]
> @xianjingfeng I found the fallback strategy is invalid. Could you help check this? CC @jerqi

I agree that we remove the pending queue. Because the concept is involved because we need to implement the function of HDFS upload.

**Comment by jerqi** [comment]
> > Of course, it's still meaningful for single storage manager.
> 
> Do you agree this?

It seems that there is little impact. It's a little complicated.

**Comment by jerqi** [comment]
@xianjingfeng WDTY?

**Comment by xianjingfeng** [comment]
I agree to remove the pending queue. We can retry write directly when we use single storage manager.

**Comment by zuston** [comment]
Let's rethink the pending queue for single storage manager. 

If the single disk is corrupted or free space is full, all events will be pushed to the pending queue, events could re-enter into flush queue once disk becomes healthy within the pending timeout. I don't know the initial design reason of this. But I think it could avoid events being dropped as much as possible, especially when disk is temporary out-of-service.

**Comment by jerqi** [comment]
> Let's rethink the pending queue for single storage manager.
> 
> If the single disk is corrupted or free space is full, all events will be pushed to the pending queue, events could re-enter into flush queue once disk becomes healthy within the pending timeout. I don't know the initial design reason of this. But I think it could avoid events being dropped as much as possible, especially when disk is temporary out-of-service.

Agree. If you insist on this, we could keep this feature. I just want to simplify this process.

**Comment by zuston** [comment]
Fixed by #383
