### ISSUE TITLE
[Improvement] Should we must set JAVA_HOME and HADOOP_HOME in rss-env.sh

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#381]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Sometimes, we have already set JAVA_HOME  and HADOOP_HOME in our system, So should we must set JAVA_HOME and HADOOP_HOME in rss-env.sh?
https://github.com/apache/incubator-uniffle/blob/897613b8022ea73d5664904bbf43fc27f93505cc/bin/rss-env.sh#L24-L25

### How should we improve?

If `JAVA_HOME` or `HADOOP_HOME`  have not be set when start server, we can just tell the users to set it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
If we dont want to use HDFS storage, `HADOOP_HOME` is not necessary.

**Comment by jerqi** [comment]
> If we dont want to use HDFS storage, `HADOOP_HOME` is not necessary.

No. We need Hadoop jar to load some Coordniator's Configurations. It's necessary..

**Comment by zuston** [comment]
> > If we dont want to use HDFS storage, `HADOOP_HOME` is not necessary.
> 
> No. We need Hadoop jar to load some Coordniator's Configurations. It's necessary..

My fault. You are right. All Hadoop filesystem operations rely on this.

**Comment by cchung100m** [comment]
Hi @xianjingfeng 

It's been a while since this issue existing and I'd like to help it if nobody is working on it currently.
