### ISSUE TITLE
[Improvement] Make coordinator class more organized

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#384]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the class in coordinator package are all in single folder. We should make coordinator class more organized, and split them into different folders by their correlation.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
cc @smallzhongfeng

**Comment by zuston** [comment]
Oh. I encounter the github bug, which creates multiple duplicate issues.

**Comment by smallzhongfeng** [comment]
Sounds great. I think it is reasonable. At present, there are many classes of coordinator, including checkers, server selection strategy, etc. we can make a unified classification.

**Comment by zuston** [comment]
Do you want to pick up this issue? @smallzhongfeng I could assign to you

**Comment by smallzhongfeng** [comment]
Ok, let me come and please assign it to me. @zuston
