### ISSUE TITLE
[Improvement] Make codec to be a singleton.

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#389]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Codec will be created for many times.  We should make codec to be a singleton.

https://github.com/apache/incubator-uniffle/blob/8847ece10a21800e5deb608441fcc6129a6b841d/common/src/main/java/org/apache/uniffle/common/compression/Codec.java#L29-L40

### How should we improve?

Make codec to be a singleton.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Will it be thread safe?

**Comment by xianjingfeng** [comment]
> Will it be thread safe?

Yes. In fact, the underlying codec is also a singleton.

**Comment by jerqi** [comment]
cc @zuston

**Comment by zuston** [comment]
The zstd and snappy codec looks OK of singleton. But LZ4Codec looks unsupported.

**Comment by xianjingfeng** [comment]
> But LZ4Codec looks unsupported.

It seems that LZ4Codec is also singleton

**Comment by jerqi** [comment]
> I'm a newbie and I want to try to solve this problem, is it possible?

Do you need any help from me?

**Comment by tobehardest** [comment]
> > I'm a newbie and I want to try to solve this problem, is it possible?
> 
> Do you need any help from me?
Maybe i need.

**Comment by jerqi** [comment]
> > > I'm a newbie and I want to try to solve this problem, is it possible?
> > 
> > 
> > Do you need any help from me?
> > Maybe i need.

Do you know Singleton pattern?  There is a example https://github.com/apache/incubator-uniffle/blob/master/internal-client/src/main/java/org/apache/uniffle/client/factory/ShuffleManagerClientFactory.java . You can refer to it.
