### ISSUE TITLE
[DOCS] Add more usage examples of quota

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#397]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
I can't get any examples to use quota limitation @smallzhongfeng . Could you help add some docs about this?

**Comment by smallzhongfeng** [comment]
For our company, users' tasks are submitted through the same platform, so many tasks may have performance bottlenecks. We will configure the parameters of rss to submit app to the uniffle cluster. However, once the rss parameters are configured, users generally do not modify them. Therefore, user may backtrack the task for a month or a whole year, and when submitting more app at the same time, other online app may be affected. Therefore, we limit users' apps to allow users to submit certain app to uniffle in batches, and the excessive app will be submitted to ESS.
