### ISSUE TITLE
Flaky Test: ShuffleBufferManagerTest#bufferSizeTest

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#408]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
[INFO] Running org.apache.uniffle.server.buffer.ShuffleBufferManagerTest
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.473 s <<< FAILURE! - in org.apache.uniffle.server.buffer.ShuffleBufferManagerTest
Error:  bufferSizeTest  Time elapsed: 0.535 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <0> but was: <288>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:628)
	at org.apache.uniffle.server.buffer.ShuffleBufferManagerTest.bufferSizeTest(ShuffleBufferManagerTest.java:428)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3681854053/jobs/6228951081

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
@zuston `ShuffleBufferManagerTest#waitForFlush` seems not applicable in this UT. because `updateCommittedBlockIds` is invoked before `event.doCleanup()`. I have no good idea to fix it. Do you have any good ideas?

https://github.com/apache/incubator-uniffle/blob/33c4fe4208b640a71d4ecbb2f9ad3f20f4ba1cc9/server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java#L211-L233

**Comment by zuston** [comment]
Another failed tests: https://github.com/apache/incubator-uniffle/actions/runs/4242048090/jobs/7373054242

**Comment by jerqi** [comment]
> @zuston `ShuffleBufferManagerTest#waitForFlush` seems not applicable in this UT. because `updateCommittedBlockIds` is invoked before `event.doCleanup()`. I have no good idea to fix it. Do you have any good ideas?
> 
> https://github.com/apache/incubator-uniffle/blob/33c4fe4208b640a71d4ecbb2f9ad3f20f4ba1cc9/server/src/main/java/org/apache/uniffle/server/ShuffleFlushManager.java#L211-L233

If this test don't have good solution, we can disable this test first to reduce the failure of CI.

**Comment by zuston** [comment]
How about sleep a while to wait `event.doCleanUp` being invoked?
