### ISSUE TITLE
[Improvement] Eliminate raw use of parameterized class

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#417]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When I'm browsing the Uniffle codebase,  a lot of raw use of parameterized class occurred, especially in test classes.

For instance, the `iterator` parameter and `product2` variable is raw use of parameterized class
https://github.com/apache/incubator-uniffle/blob/66c752fe3ecd6d4979d3539fe22265d4239156a9/client-spark/common/src/test/java/org/apache/spark/shuffle/reader/AbstractRssReaderTest.java#L51-L63

### How should we improve?

Eliminate the raw use of parameterized class as much as possible.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cchung100m** [comment]
Hi @advancedxy 

I'd like to handle this issue if you agreed. Thank you.

**Comment by jerqi** [comment]
I assigned to you.
