### ISSUE TITLE
[Improvement] Separate HDFS and LocalDisk flush thread pool

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#425]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The writing speed gap is obvious in HDFS and local disk, it's better to avoid sharing the same thread pool.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
cc @advancedxy @xianjingfeng @jerqi

**Comment by jerqi** [comment]
It's ok for me. We should have a clear design, I event have similar idea , but I can't give reasonable abstraction.

**Comment by zuston** [comment]
> I think we should add a priority thread pool too.

Could you help describe more? @xianjingfeng

**Comment by xianjingfeng** [comment]
> > I think we should add a priority thread pool too.
> 
> Could you help describe more? @xianjingfeng

In our production environment, some jobs are important and need to be handled first.

**Comment by zuston** [comment]
> In our production environment, some jobs are important and need to be handled first.

Make sense.

**Comment by zuston** [comment]
If you have interest on this, feel free to pick it up @xianjingfeng

**Comment by xianjingfeng** [comment]
> If you have interest on this, feel free to pick it up @xianjingfeng

I don't have time recently, because I have other tasks. If no one is willing to do it, I will do it when I am free next year.

**Comment by zuston** [comment]
> I don't have time recently, because I have other tasks. If no one is willing to do it, I will do it when I am free next year.

Feel free to take this If you will @xianjingfeng. And I think this is a valuable improvement.
