### ISSUE TITLE
[Improvement] New utility method to cover dynamic class loading in RSSUtils

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#434]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?
New utility method to cover dynamic class loading.

_Originally posted by @xianjingfeng in https://github.com/apache/incubator-uniffle/pull/415#discussion_r1050526428_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pegasas** [comment]
It seems this issue has clear roadmap for first good issue.
Could you please assign me this issue? Thanks.

**Comment by jerqi** [comment]
> It seems this issue has clear roadmap for first good issue. Could you please assign me this issue? Thanks.

Yes, thanks. Assigned to you.
