### ISSUE TITLE
[Improvement] Reuse HDFS client FSDataOutputStream to avoid extra overhead

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#440]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In `HdfsShuffleWriteHandler,` it will always create the instance of `HdfsFileWriter` to write data, in which, the  FSDataOutputStream will connect or close with remote NN. 

There is no need to close every time, we could reuse this to speed up.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
How to process when we fail to write HDFS?

**Comment by zuston** [comment]
> How to process when we fail to write HDFS?

Invalidate this cache.

**Comment by jerqi** [comment]
If you don't close, you can't guarantee that the data is safe. you can't delete the memory data.

**Comment by zuston** [comment]
> If you don't close, you can't guarantee that the data is safe. you can't delete the memory data.

The operation of `flush` can't guarantee this?

**Comment by jerqi** [comment]
> > If you don't close, you can't guarantee that the data is safe. you can't delete the memory data.
> 
> The operation of `flush` can't guarantee this?

The cost of flush operation is similar to the operation close.

**Comment by zuston** [comment]
> The cost of flush operation is similar to the operation close.

But this could avoid re-creating with the datanode when flushing events again. Right?

**Comment by zuston** [comment]
> If the data is flushed successfully, but the data is close unsuccessfully, how to process this case?

If it could be read by downstream reducer once flushed, we could accept its close failure. But I'm not sure whether the  flushing operation could guarantee the visibility

**Comment by xianjingfeng** [comment]
Not every events will flush to hdfs. In our production environment, the probability that  flush to hdfs is less than 1 in 1000. So i think if this feature is required, it can be used as an option.

**Comment by zuston** [comment]
> Not every events will flush to hdfs. In our production environment, the probability that flush to hdfs is less than 1 in 1000. So i think if this feature is required, it can be used as an option.

Yes. Actually, I don't know the real performance improvement for this feature, maybe I won't raise a PR to solve
