### ISSUE TITLE
[Improvement] refactor getPartitionRange to calculate range directly

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#443]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

ShuffleStorageUtils.getPartitionRange is not performant...

It could be calculated directly in O(1).. However current impl is about O(n) where n is the number of partition ranges. when partition range size =1, n is corresponding to partition numbers.

### How should we improve?

refactor `ShuffleStorageUtils.getPartitionRange` to calculate range directly.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by a-li** [comment]
Hey I’m looking to contribute to Uniffle and would like to try to do this task.
