### ISSUE TITLE
[Improvement]  Lazily create `uncompressedData`

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#455]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

This part as follows will cost much memory if we use AQE. We should create `uncompressedData` lazily.
https://github.com/apache/incubator-uniffle/blob/9572b8423fff8f3dfa52411dae1caa4d33f08663/client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java#L73-L78

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
PTAL @zuston

**Comment by zuston** [comment]
Nice catch, could you help fix this?

**Comment by jerqi** [comment]
closed by #457
