### ISSUE TITLE
[Improvement]  Exit on OutOfMemoryError

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#460]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

At present, if OutOfMemoryError is encountered, server will not exit.

### How should we improve?

Add `-XX:+ExitOnOutOfMemoryError` and `-XX:+CrashOnOutOfMemoryError` to JVM argments.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
PTAL @jerqi @zuston @advancedxy

**Comment by jerqi** [comment]
> PTAL @jerqi @zuston @advancedxy

Do we need dump the memory when OOM occurs。

**Comment by xianjingfeng** [comment]
> > PTAL @jerqi @zuston @advancedxy
> 
> Do we need dump the memory when OOM occurs？

The dump file maybe too big and disk space may be not enough to store it. So users should specify the path to store it.

**Comment by zuston** [comment]
> The bin/start-shuffle-server.sh may handle that as a cli argument or env variable.

Good idea. This should be supported.

**Comment by AdarshRawat1** [comment]
![image](https://user-images.githubusercontent.com/100958893/226178946-c0aa7f3e-b1dd-46c2-8419-5d038ee14f4f.png)

**Comment by jerqi** [comment]
> Requesting permission to contribute to this feature. . Can you please advise on how I can get involved? Thanks
I assign this issue to you.

@AdarshRawat1 You can refer to https://github.com/apache/incubator-uniffle/blob/master/CONTRIBUTING.md
If you have any question, you can ask me.

**Comment by AdarshRawat1** [comment]
Could you kindly provide me with additional resources and guidance [files to change, Tests to perform], please?

**Comment by jerqi** [comment]
1. files to change
https://github.com/apache/incubator-uniffle/blob/master/bin/start-coordinator.sh
https://github.com/apache/incubator-uniffle/blob/master/bin/start-shuffle-server.sh
2.test to perform
You build package and unzip it, set environment variable (JAVA_HOME and HADOOP_HOME) and run the cmd
`sh bin/start-shuffle-server.sh` and `sh bin/start-coordinator.sh`. If the process start successfully, the change is ok.

**Comment by jerqi** [comment]
@AdarshRawat1 Do you need any other help from me?

**Comment by jerqi** [comment]
> > @AdarshRawat1 Do you need any other help from me?
> 
> @jerqi I’m currently occupied with my mid-term exams. Once I’m done with them, I’ll address this issue. I would appreciate your valuable guidance at that time. Thank you.

@AdarshRawat1 Do you want to continue this issue?

**Comment by AdarshRawat1** [comment]
@jerqi I deeply regret the delay and will commence work on it today. I look forward to receiving your guidance throughout the process.

**Comment by AdarshRawat1** [comment]
@jerqi I apologize, but I'm unable to work on this issue.
