### ISSUE TITLE
[FEATURE] Spark 3.3 support

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#461]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support Spark 3.3 in Uniffle.

### Motivation

Spark 3.3 has been released in Jun 16, 2022.
Users are going to migrate to Spark 3.3 sooner or later.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
> Would you like to submit a PR here? Or do you encounter some issues?

I'm not sure.

> I was expected we can simply use spark 3.2 support to run spark 3.3 apps as Spark 3.3 doesn't change the APIs..

In this case, we should add test profile for Spark 3.3 and enable them in CI.

**Comment by zuston** [comment]
Make sense.

**Comment by kaijchen** [comment]
Plus: we may need to create a patch for spark 3.3 in https://github.com/apache/incubator-uniffle/tree/master/spark-patches

**Comment by kaijchen** [comment]
I'm not sure if I added the profile correctly, seems spark 3.3 requires some test code change:
https://github.com/kaijchen/incubator-uniffle/actions/runs/3873117861/jobs/6602763685#step:8:8

**Comment by kaijchen** [comment]
Closed by #463.
