### ISSUE TITLE
[Improvement] It's unnecessary to use ConcurrentHashMap for "partitionToBlockIds" in RssShuffleWriter

### ISSUE THREAD

**Issue by zjf2012** [apache/incubator-uniffle#475]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For RssShuffleWriter, each task has unique instance of RssShuffleWriter. Thus, there is only one thread access its field, "partitionToBlockIds". It's inappropriate to use ConcurrentHashMap and ConcurrentHashSet like below.
`
this.partitionToBlockIds = Maps.newConcurrentMap();

partitionToBlockIds.putIfAbsent(partitionId, Sets.newConcurrentHashSet());
`

### How should we improve?

We can just use simple HashMap and HashSet which avoid unnecessary locks.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Will it bring too much cost?

**Comment by zjf2012** [comment]
> Will it bring too much cost?

I cannot tell how much cost it is. But you can imagine we need to get lock first before each map operation in each shuffle write partition. And it's counter-intuitive to use lock whilst it's unnecessary. We should avoid lock as much as possible.

**Comment by jerqi** [comment]
If there is no thread conflicts, the clock operation only cost ns.

**Comment by zjf2012** [comment]
> If there is no thread conflicts, the clock operation only cost ns.

maybe. There is other potential side-effect, like flushing CPU buffer to memory due to lock involved. So, it's better to avoid lock.

**Comment by zjf2012** [comment]
> I'm in favor of this. The following code path doesn't need a ConcurrentHashMap as well.
> 
> https://github.com/apache/incubator-uniffle/blob/ddf83843a9fbce8155d159815c351b16eb5a9704/client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java#L476

I just re-checked the code. It's different case since the shuffleWriteClientImpl instance is created in RssshuffleManager and shared by different threads. So, it's reasonable to use concurrenthashmp here.

**Comment by zjf2012** [comment]
> The groupedPartitions is a local variable, it will never be used across threads?

correct. let me fix it along with RssShuffleWriter.
