### ISSUE TITLE
[FEATURE] Respect "spark.shuffle.compress" configuration in Uniffle

### ISSUE THREAD

**Issue by zjf2012** [apache/incubator-uniffle#476]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

In Spark, there is a configuration, "spark.shuffle.compress", to control if we should compress shuffled data. It defaults to true. But Uniffle always compresses shuffled data without respecting the configuration. Uniffle should respect it to be more align with vanilla Spark.

### Motivation

We should let user decide if compress can be applied since some workloads are not compress friendly which otherwise can avoid useless CPU cycles.

### Describe the solution

We can check "spark.shuffle.compress" configuration in WriteBufferManager and RssShuffleDataIterator before compressing and decompressing.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Some compress algorithms which  Uniffle supports may be different from Spark's.

**Comment by zjf2012** [comment]
> Some compress algorithms which Uniffle supports may be different from Spark's.

It's not related to Spark's compress alg. since rss shuffle manager are separated from Spark's shuffle manager. But it's about whether you want to give user a choice to decide compress or not. It seems that there is a delegationShuffleManager which delegates to Spark's default shuffle manager in some cases. It may cause inconsistency among shuffle managers in regard to the compress configuration.

**Comment by jerqi** [comment]
> > Some compress algorithms which Uniffle supports may be different from Spark's.
> 
> It's not related to Spark's compress alg. since rss shuffle manager are separated from Spark's shuffle manager. But it's about whether you want to give user a choice to decide compress or not. It seems that there is a delegationShuffleManager which delegates to Spark's default shuffle manager in some cases. It may cause inconsistency among shuffle managers in regard to the compress configuration.

Ok, I get your point.

**Comment by zuston** [comment]
> I believe Uniffle uses org.apache.uniffle.common.compression.Codec.NOOP to disable compress. But it's never used in production and may have other hidden issues. cc @zuston.

NOOP is just for test now.

**Comment by jerqi** [comment]
closed by #495
