### ISSUE TITLE
[Improvement] [Operator] better build system support

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#479]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1. support RSS operator build on M1 MacBook Pro
2. docker-build and docker-push defaults to docker.io?
3. Commit new code-generated changes
4. replace alpine with Google's distroless containers since alpine uses `musl`, which is hard to used glibc related program

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
2. We would better not do this because binary image release also need a vote process to release the binary image.
4. It seems that we don't use alpine.

**Comment by jerqi** [comment]
> > 2 We would better not do this because binary image release also need a vote process to release the binary image.
> > 4 It seems that we don't use alpine.
> 
> For 2, I don’t mean we should release a docker image now, rather have a better default settings that make build-docker works without setting registry explicitly. We can consider releasing office image when there’s more people asking it. For 4, the dockerfile uses alpine.

We use `openjdk:8-jdk-slim`.
