### ISSUE TITLE
[Improvement] Replace putIfAbsent with computeIfAbsent in some critical paths

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#493]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

This problem is mentioned by previous PR https://github.com/apache/incubator-uniffle/pull/481#discussion_r1070752457.

The invoking of `putIfAbsent` will always call its value if it's a time-consuming operation. So we'd better replace putIfAbsent with computeIfAbsent in some critical paths.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pushkarmondal** [comment]
is this issue resolved?
Hey how can I contribute to this ?

**Comment by cchung100m** [comment]
Hi @zuston 

I'd like to handle this issue if you agreed.  Thank you.

**Comment by zuston** [comment]
@cchung100m Assigned. Thanks in advance
