### ISSUE TITLE
[Subtask][operator] set init-container's resource request

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#496]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

uniffle's rss operator generate init-container without resource requirement, which normally could be acceptable. 
But when deployed to namespace with resource quota, every pod should set its resource request, otherwise the controller could reject the pod creation.

Therefore rss operator should set coordinator and shuffle server's init-container with resource request inferred.

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/807537/213104431-33e4699c-7173-4743-a4c8-7516b578a26f.png">

### Parent issue

#462 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Do you mean uniffle should set the default resource request? like that

![image](https://user-images.githubusercontent.com/8609142/213128323-dd4a05d3-24de-4b23-bec3-d996f7c6389e.png)
