### ISSUE TITLE
[Subtask] [operator] expose more fields for RSS

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#545]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

> expose more fields in operator's CRD, such as RuntimeClassName, Tolerations, Annotation and Affinity, etc. Therefore the shuffle server cloud be deployed more flexible

Quoted from parent issue.

### Parent issue

#462

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wangao1236** [comment]
Ok, I'll do it.
