### ISSUE TITLE
[Improvement][Style] add autolink to issues in PR title and commit msg

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#551]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It's common and considered best practice to be able to click links to corresponding issues/PRs/tickets in the commit msg. To achieve this features, Github's autolinked references and links[^1] are used. 

For example, Spark uses this feature to autolink Jiras. 
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/807537/216869357-205d4cfb-7a37-47a4-beba-fef632399e57.png">

Since Uniffle are using Github Issues to track issues/request/improvements, etc. The issue is effective the same as the Jira ticket.

I'd like to propose an suggestion to improve the code context experience: add autolink to issues in PR title and commit msg.

[^1]: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls

### How should we improve?

1. Let's decide which form to include autolinks:
   - [#xxx], the simple form, https://github.com/apache/incubator-uniffle/commit/cf9afab471a9595d8298ebd65c4d25c080ad4bbf
     <img width="956" alt="image" src="https://user-images.githubusercontent.com/807537/216869878-3023c60d-b64c-46eb-a631-47c8dd6eb915.png"> 
   - [ISSUE #xxx] prefixed with the `ISSUE`
2. Enforce the pr title check.  Every PR should have an issue linked. 
    There's an exception rule for this: PR title prefixed with [Minor]/[MINOR] can be excused for this enforcement check.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Can we use the apache style like `[UNIFFLE-120][Test] Fix msg` ? And the `uniffle-120 `could be linked to github issue by https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources

**Comment by kaijchen** [comment]
`UNIFFLE-120` may be confusing, because it's usually a Jira id.
Currently I would not recommend Jira because the self registration is limited. We wish to make new contributors easier to join the project.
For how to configure the autolink, see https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

**Comment by kaijchen** [comment]
> The point to add issue id in the title is that we can links to issues and commits in Github's ecosystem. In most cases, only title is displayed for commits.

My point is, by just looking at the issue id, you don't get any information. 
When looking at commit history, you got interested by the scope and type of the change first.
Then you start to looking for why it's needed, and find the related issue.

Just click the 3 dots, you could see it the description.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/5821159/216879627-99b96924-c86e-4d3f-83ec-0a6f880d1836.png">

**Comment by jerqi** [comment]
It's ok for me.

**Comment by zuston** [comment]
It's OK for me, thanks for your effort. @advancedxy

**Comment by xianjingfeng** [comment]
> > kaijchen zuston jerqi felixcheung WDYT?
> 
> also cc @xianjingfeng which was pointed to a wrong one.

It's OK for me.

**Comment by kaijchen** [comment]
Seems the following format is preferred now?

```
[#123] feat: add xxx feature
[#124] fix: exception in xxx 
```

**Comment by kaijchen** [comment]
How about combine issue ID and [semantic commit message][1] ?

```
[<issue>]<type>(<scope>): <subject>
```

For example:
```
[#123]feat(operator): support feature xxx
[minor]refactor: fix typo in variable name
```

[1]: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

**Comment by kaijchen** [comment]
Hi everyone, I've edited existing open PR titles (to show examples to new PR). How do you think?

<img width="732" alt="screenshot" src="https://user-images.githubusercontent.com/5821159/218024535-ac1a4c96-57a5-42cd-bd21-30148df4e5a5.png">
