### ISSUE TITLE
[Improvement] Integration test for operator

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#564]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We should run integration test for operator on CI/github actions

### How should we improve?

add integration tests by leverage KIND or minukube.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wangao1236** [comment]
Okay, I'll take care of that. Assign me the issue please.
