### ISSUE TITLE
[Subtask] [Netty] Implementation of basic framework.

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#582]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

Implementation of basic framework is used for netty to replace grpc, mainly including Encoder and Decoder, and we can't affect the existing grpc framework.
The document link is as follows:
https://docs.google.com/document/d/1srlBlLpJ3hbzd8ru5QaY5aCSLR9M2ttHXmlvcFC-SLg/edit?usp=sharing

### Parent issue

https://github.com/apache/incubator-uniffle/issues/133

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Closed.
