### ISSUE TITLE
[Subtask] [Netty] Implementation of client connection management

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#584]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

To realize the connection management of the client, such as [https://github.com/apache/spark/blob/master/common/network-common/src/main/java/org/apache/spark/network/client/TransportClientFactory.java](url).
The document link address is as follows:
https://docs.google.com/document/d/1srlBlLpJ3hbzd8ru5QaY5aCSLR9M2ttHXmlvcFC-SLg/edit?usp=sharing

### Parent issue

https://github.com/apache/incubator-uniffle/issues/133

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
assgin for me,thx

**Comment by leixm** [comment]
@xumanbu  Can you submit a PR?
