### ISSUE TITLE
[Subtask] [Netty] Support ShuffleServer to use off-heap memory to manage shuffle data

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#586]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

ShuffleServer supports using off-heap memory to manage shuffle data and reduce gc time.
The document link address is as follows:
https://docs.google.com/document/d/1srlBlLpJ3hbzd8ru5QaY5aCSLR9M2ttHXmlvcFC-SLg/edit?usp=sharing

### Parent issue

https://github.com/apache/incubator-uniffle/issues/133

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@summaryzb

**Comment by summaryzb** [comment]
ok，I‘m working on it

**Comment by jerqi** [comment]
@summaryzb Any progress?
