### ISSUE TITLE
[Subtask] [Netty] Support zero copy to read local file

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#590]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

We use zero copy api to read data and send the data to network. We can refer to Spark, Kafka, etc system.
We should remove read memory.

### Parent issue

#133

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
Could you assign this to me? I'm trying to make changes here. @jerqi

**Comment by leixm** [comment]
@jerqi  @smallzhongfeng This PR will rely on Netty's Encoder support, After completing the Basic framework, I will implement the relevant Decoder, like:
https://github.com/apache/incubator-celeborn/blob/main/common/src/main/java/org/apache/celeborn/common/network/protocol/MessageEncoder.java
https://github.com/apache/incubator-celeborn/blob/main/common/src/main/java/org/apache/celeborn/common/network/protocol/MessageWithHeader.java

**Comment by jerqi** [comment]
@smallzhongfeng Encoder and Decoder is ready. You can continue this issue.
