### ISSUE TITLE
Change the default branch name from master to main

### ISSUE THREAD

**Issue by frankliee** [apache/incubator-uniffle#61]
"master" may have some unfriendly meanings, as an alternative, many new projects have leveraged "main".

**Comment by jerqi** [comment]
I think it's not a big problem. Apache Spark and Apache Flink also use the name `master`.

**Comment by frankliee** [comment]
They are old projects, new projects like Gluten/Velox use "main", and Github's default branch for new projects are "main".

**Comment by jerqi** [comment]
There are also many new projects that use the name `master`.

**Comment by colinmjj** [comment]
Besides master, words like 'blacklist', 'slave' also shouldn't be used in code to avoid problem.

**Comment by jerryshao** [comment]
I don't think this is a problem,  and we should spend time on such things.
