### ISSUE TITLE
[Improvement] run CIs based on paths changed

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#626]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For JVM only related changes, we don't have to run k8s/operator build. We can leverage https://github.com/dorny/paths-filter#examples to achieve this.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
Ref #580.
