### ISSUE TITLE
[FEATURE] Disable the localShuffleRead in Spark client

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#630]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

The conf of `spark.sql.adaptive.localShuffleReader.enabled` should be false when using uniffle.

We'd better to disable it by default in `RssShuffleManager`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
PTAL @jerqi @advancedxy

**Comment by jerqi** [comment]
Ok for me.
