### ISSUE TITLE
[Improvement] Enable LOCAL_ORDER for Spark AQE by default

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#635]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the local_order data distribution type should be activated explicitly. It's better to enable it when using AQE by default.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
cc @jerqi @advancedxy

**Comment by jerqi** [comment]
+1
