### ISSUE TITLE
[Subtask] [Netty] Metrics system

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#640]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

We should more Netty metrics to ensure our system load. 

### Parent issue

#133

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
assgin for me,thx
