### ISSUE TITLE
[Improvement] better default shuffle server configuration 

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#642]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1. `rss.server.buffer.capacity` could have a default settings, `JVM MaxHeapSize` * some factor
2. `rss.server.read.buffer.capacity` is similar with `rss.server.buffer.capacity`

Otherwise, once the max heap size of shuffle server is changed, users/admins have to reconfigure these two buffer settings.

----
1. `rss.server.disk.capacity` is -1(by default), shuffle server uses the total space of one disk, which seems operation unfriendly. Shuffle server should reserve some partition of disk space and not use all the disks, such as at most 95% the capacity. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
> cc @jerqi, WDYT? would you like to refine this settings?

OK

**Comment by zuston** [comment]
> rss.server.disk.capacity is -1(by default), shuffle server uses the total space of one disk, which seems operation unfriendly. Shuffle server should reserve some partition of disk space and not use all the disks, such as at most 95% the capacity.

I think this config as a ratio value will be better, the current concrete disk capacity is not flexible especially for heterogeneous storage.
