### ISSUE TITLE
[Bug]  Probloms of `RequireUpperBoundDeps`

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#685]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The following message is output after executing  ./build_distribution.sh

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.protobuf:protobuf-java:3.19.2 paths to dependency are:
+-org.apache.uniffle:rss-integration-common-test:0.8.0-SNAPSHOT
  +-org.apache.uniffle:shuffle-server:0.8.0-SNAPSHOT
    +-io.grpc:grpc-protobuf:1.47.0
      +-com.google.protobuf:protobuf-java:3.19.2
and
+-org.apache.uniffle:rss-integration-common-test:0.8.0-SNAPSHOT
  +-org.apache.uniffle:rss-common:0.8.0-SNAPSHOT
    +-org.apache.uniffle:rss-proto:0.8.0-SNAPSHOT
      +-com.google.protobuf:protobuf-java-util:3.19.6
        +-com.google.protobuf:protobuf-java:3.19.6
and
+-org.apache.uniffle:rss-integration-common-test:0.8.0-SNAPSHOT
  +-org.apache.uniffle:shuffle-server:0.8.0-SNAPSHOT
    +-io.grpc:grpc-protobuf:1.47.0
      +-com.google.api.grpc:proto-google-common-protos:2.0.1
        +-com.google.protobuf:protobuf-java:3.13.0
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
Would you help to fix this problom? @kaijchen  And i think workflow should cover this case.

**Comment by kaijchen** [comment]
> Would you help to fix this problom? @kaijchen And i think workflow should cover this case.

I have no problem building it. Please run `maven clean` and remove anything in `~/.m2/repository/org/apache/uniffle/`

**Comment by xianjingfeng** [comment]
> > Would you help to fix this problom? @kaijchen And i think workflow should cover this case.
> 
> I have no problem building it. Please run `maven clean` and remove anything in `~/.m2/repository/org/apache/uniffle/`

I just tried it, the problem still exists. Could it be a maven version issue?
Maven version: 3.6.1

**Comment by kaijchen** [comment]
> I just tried it, the problem still exists. Could it be a maven version issue?
> Maven version: 3.6.1

I'm using maven 3.6.3.
Full build log: https://paste.ubuntu.com/p/YSzJyCCs3B/

**Comment by xianjingfeng** [comment]
I have try different devices and different maven version, but neither work. I had to modify the dependency file.
Is it just me having this problem? 😂  cc @jerqi @zuston @advancedxy  @smallzhongfeng

**Comment by jerqi** [comment]
I encounter the same problem with maven 3.6.1. It's ok for me to use 3.6.3.

**Comment by xianjingfeng** [comment]
> I encounter the same problem with maven 3.6.1. It's ok for me to use 3.6.3.

3.6.3 does work now, but 3.3.9 and 3.6.1 don't. It seems that versions below 3.6 have this problem. Should we fix this issue? Just modify dependency file.
