### ISSUE TITLE
[Improvement] Fine-grained memory control for spark client

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#706]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1. #714 
2. Introduce dedicated `memoryConsumer` when fetching remote data, especially for after supporting async read. #291 
3. ...

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
And I also find that some apps in our production failed due to requiring memory failed, but it works well with ESS, although the available memory is less in ESS.

**Comment by zuston** [comment]
cc @jerqi @advancedxy

**Comment by jerqi** [comment]
Ok for me.

**Comment by zuston** [comment]
> And I also find that some apps in our production failed due to requiring memory failed, but it works well with ESS, although the available memory is less in ESS.

And the available memory is tight, could we support append record to temp files and at the final step, send them to remote shuffle-server, rather than using memory to hold them.
