### ISSUE TITLE
[Improvement]LocalStorage init use multi thread

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#71]
We have multi disk in a host. If shuffle server exit abnormally, there will be many files need to be clear when shuffle server start again and this operation will cost a lot of time

**Comment by jerqi** [comment]
How much time will it take to execute the operation? Could you provide some concrete data?

**Comment by jerqi** [comment]
How much time will it take to execute the operation? Could you provide some concrete data?

**Comment by colinmjj** [comment]
@xianjingfeng I think clear unnecessary data before start shuffle server by Linux command is a better way, and clear process during shuffle server startup is a backup solution.
I prefer to improve start script to do such thing.

**Comment by xianjingfeng** [comment]
> How much time will it take to execute the operation? Could you provide some concrete data?

more that 30 seconds per disk, it dependency disk performance and usage.

**Comment by jerqi** [comment]
> > How much time will it take to execute the operation? Could you provide some concrete data?
> 
> more that 30 seconds per disk, it dependency disk performance and usage.

What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.

**Comment by xianjingfeng** [comment]
> > > How much time will it take to execute the operation? Could you provide some concrete data?
> > 
> > 
> > more that 30 seconds per disk, it dependency disk performance and usage.
> 
> What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.

hdd, about 1T usage per disk

**Comment by xianjingfeng** [comment]
> @xianjingfeng I think clear unnecessary data before start shuffle server by Linux command is a better way, and clear process during shuffle server startup is a backup solution. I prefer to improve start script to do such thing.

if do this in start scirpt, we need parse conf file in start script, i think it is heavy for start script and it is difficult to maintain

**Comment by xianjingfeng** [comment]
> > > How much time will it take to execute the operation? Could you provide some concrete data?
> > 
> > 
> > more that 30 seconds per disk, it dependency disk performance and usage.
> 
> What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.

FileUtils.deleteDirectory will delete it's childrens first

**Comment by jerqi** [comment]
> > > > How much time will it take to execute the operation? Could you provide some concrete data?
> > > 
> > > 
> > > more that 30 seconds per disk, it dependency disk performance and usage.
> > 
> > 
> > What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.
> 
> FileUtils.deleteDirectory will delete it's childrens first

Ok, I got it. It's ok for me to use multi-thread to do cleanup operation.

**Comment by frankliee** [comment]
> > > > How much time will it take to execute the operation? Could you provide some concrete data?
> > > 
> > > 
> > > more that 30 seconds per disk, it dependency disk performance and usage.
> > 
> > 
> > What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.
> 
> FileUtils.deleteDirectory will delete it's childrens first



> > > > How much time will it take to execute the operation? Could you provide some concrete data?
> > > 
> > > 
> > > more that 30 seconds per disk, it dependency disk performance and usage.
> > 
> > 
> > What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.
> 
> hdd, about 1T usage per disk

How many files are deleted in your disk ?  Uniffle has merged data in each partition, so there will not exist very large number of files. Can you do a simple test by using `rm -rf`？

**Comment by xianjingfeng** [comment]
> 



> > > > > How much time will it take to execute the operation? Could you provide some concrete data?
> > > > 
> > > > 
> > > > more that 30 seconds per disk, it dependency disk performance and usage.
> > > 
> > > 
> > > What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.
> > 
> > 
> > FileUtils.deleteDirectory will delete it's childrens first
> 
> > > > > How much time will it take to execute the operation? Could you provide some concrete data?
> > > > 
> > > > 
> > > > more that 30 seconds per disk, it dependency disk performance and usage.
> > > 
> > > 
> > > What's the type of disk that you use? The performance of disk is a little strange. We only delete one directory on every disk, it shouldn't take so much time.
> > 
> > 
> > hdd, about 1T usage per disk
> 
> How many files are deleted in your disk ? Uniffle has merged data in each partition, so there will not exist very large number of files. Can you do a simple test by using `rm -rf`？

I neither count how many files nor test by using rm -rf , i will try to do this recently

**Comment by jerqi** [comment]
solved by pr #72
