### ISSUE TITLE
[Bug] problems of RssMapOutputCollector

### ISSUE THREAD

**Issue by zhaobing001** [apache/incubator-uniffle#715]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The connection between the client and shufflerserver is not closed. As a result, the maptask container does not exit.
1.map container does not exit when reduce is running
2.When cluster resources are used up and some maps are not allocated, am waits for a one-minute timeout, kills the completed map container, and allocates resources to other maps

error log like:
2023-03-11 02:42:16,826 INFO [Ping Checker] org.apache.hadoop.yarn.util.AbstractLivelinessMonitor: Expired:attempt_1676901654399_1531374_m_000190_0 Timed out after 60 secs

In the close method of the RssMapOutputCollector, closing the shuffle client solves this problem

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Is it a occassional case?

**Comment by zhaobing001** [comment]
> 

An inevitable case

**Comment by jerqi** [comment]
Could you raise a pr to fix this issue?

**Comment by jerqi** [comment]
closed by #882
