### ISSUE TITLE
[Subtask] [Netty] Optimize allocation strategy

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#719]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

When we use Netty servers., there are Netty servers and Grpc servers at the same time at first in our production. We should allocate different servers to client according to ClientType. We allocate Netty servers to `GrpcNetty` client. We allocate Grpc servers to `Grpc` client.

### Parent issue

#133

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
@smallzhongfeng Could you help solve this issue?

**Comment by smallzhongfeng** [comment]
So future servers only need to reserve one port, right ?

**Comment by jerqi** [comment]
> So future servers only need to reserve one port, right ?

They will reserve two ports. But if we enable Netty, we will only use Netty to transfer data.
