### ISSUE TITLE
[Improvement] ShuffleBufferManager.flushSingleBufferIfNecessary unreasonable

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#756]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

After #471 , the data size of a single partition reaches rss.server.huge-partition.size.threshold, can flush be triggered without waiting for rss.server.single.buffer.flush.threshold satisfy.
https://github.com/apache/incubator-uniffle/blob/master/server/src/main/java/org/apache/uniffle/server/buffer/ShuffleBufferManager.java#228
`if ((isHugePartition || this.bufferFlushEnabled) && buffer.getSize() > this.bufferFlushThreshold) {`

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by leixm** [comment]
@zuston  PTAL.

**Comment by zuston** [comment]
It’s my mistake, could you help fix?

**Comment by leixm** [comment]
cc @zuston

**Comment by zuston** [comment]
> I misunderstood just now, the single-partition flush still takes effect, but when the data size of a single partition reaches rss.server.huge-partition.size.threshold, can flush be triggered without waiting for rss.server.single.buffer.flush.threshold satisfy.

Yes. I have rechecked, this is reasonable. WDYT?

**Comment by leixm** [comment]
Misunderstood before, seems reasonable, I will close this issue.
