### ISSUE TITLE
[Subtask] `Cli` method for blacklist update

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#768]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

Currently, updates to the blacklist need to rely on the scheduling thread pool for updates, which is relatively inefficient. We can emulate the Hadoop method of updating the config and add clis for updates, which is more efficient.

### Parent issue

#758 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Kwafoor** [comment]
I'm Interested in this, could you assign it to me？Should I wait for [770](https://github.com/apache/incubator-uniffle/issues/770) to be completed before starting?

**Comment by smallzhongfeng** [comment]
Of course, I assigned it to you.

**Comment by smallzhongfeng** [comment]
> I'm Interested in this, could you assign it to me？Should I wait for [770](https://github.com/apache/incubator-uniffle/issues/770) to be completed before starting?

Yes, try to wait for #770 to complete.

**Comment by jerqi** [comment]
cc @Kwafoor #770 has been finished. You can go ahead.

**Comment by Kwafoor** [comment]
> cc @Kwafoor #770 has been finished. You can go ahead.

OK，I will finish as soon as possible.

**Comment by Kwafoor** [comment]
> cc @Kwafoor #770 has been finished. You can go ahead.

Almost done, just a little more checking and final touches left. I'll submit it in a few days.

**Comment by jerqi** [comment]
> > cc @Kwafoor #770 has been finished. You can go ahead.
> 
> Almost done, just a little more checking and final touches left. I'll submit it in a few days.

We usually use rest api to control admin service. If we need add api, we would better add rest api. Could we keep consistent with other operation. You can refer to https://github.com/apache/incubator-uniffle/pull/684

**Comment by Kwafoor** [comment]
>  I have implemented control admin service with reference to yarn through grpc, but I will refer to #684 to see how to achieve it through rest.

**Comment by Kwafoor** [comment]
> > > cc @Kwafoor #770 has been finished. You can go ahead.
> > 
> > 
> > Almost done, just a little more checking and final touches left. I'll submit it in a few days.
> 
> @Kwafoor We usually use rest api to control admin service. If we need add api, we would better add rest api. Could we keep consistent with other operation. You can refer to #684

I have implemented control admin service with reference to yarn through grpc, but I will refer to https://github.com/apache/incubator-uniffle/pull/684 to see how to achieve it through rest.

**Comment by jerqi** [comment]
closed by #931
