### ISSUE TITLE
[Feature Request] Support deploy multiple shuffle servers in a single node 

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#77]
We have 1.2T memory per host, so we need deploy multiple shuffle servers in a single node.
But current partition assignment policy is not suitable to do that. 
Because partition maybe assign to a same host and client maybe fail if one host down

**Comment by zuston** [comment]
As i know, partition assignment policy could be implemented by yourself.

**Comment by xianjingfeng** [comment]
> As i know, partition assignment policy could be implemented by yourself.

Yes, but not only assignment policy need to be change, such as start script, i will create a pr for this

**Comment by jerqi** [comment]
I'm also curious why we need to modify start script?

**Comment by xianjingfeng** [comment]
> I'm also curious why we need to modify start script?

start script will process existence

**Comment by xianjingfeng** [comment]
If our plan is deploy on k8s, this issue should close?

**Comment by jerqi** [comment]
K8S Deployment can't solve this issue.

**Comment by colinmjj** [comment]
> > I'm also curious why we need to modify start script?
> 
> start script will process existence

Yes, this is the limit with current implementation

**Comment by jerqi** [comment]
> K8S Deployment can't solve this issue.

@xianjingfeng I think you can continue this.

**Comment by xianjingfeng** [comment]
> > K8S Deployment can't solve this issue.
> 
> @xianjingfeng I think you can continue this.

ok
