### ISSUE TITLE
[Subtask] Introduce `apache.commons.cli` basic framework

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#770]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the subtask

We can imitate `YarnCli` to build a `UnifleCli`.

### Parent issue

#758 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by slfan1989** [comment]
@smallzhongfeng Can I assign this issue? Thank you very much!

**Comment by slfan1989** [comment]
I will submit the code of version 1 in the next 1-2 days.

**Comment by smallzhongfeng** [comment]
Fixed by https://github.com/apache/incubator-uniffle/pull/833
