### ISSUE TITLE
[FEATURE] Separate `ShuffleServer` metrics through tags

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#778]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

In the production environment, we have introduced tag, with the metrics of accessing Grafana. In order to better distinguish the metrics of shuffle-server with different tags, we need to separate them.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
PTAL. @jerqi @zuston If necessary, I will raise a pr.

**Comment by jerqi** [comment]
> PTAL. @jerqi @zuston If necessary, I will raise a pr.

OK for me.

**Comment by zuston** [comment]
Put `tag` into `labelNames` of metrics ? @smallzhongfeng

**Comment by smallzhongfeng** [comment]
Yes, currently our environment does this. @zuston

**Comment by smallzhongfeng** [comment]
![image](https://user-images.githubusercontent.com/84573424/231085826-7eb21462-5a8d-46c6-96df-14b4e2908483.png)

**Comment by smallzhongfeng** [comment]
Just like this. Does this meet your expectations ? @zuston @jerqi

**Comment by jerqi** [comment]
> Just like this. Does this meet your expectations ? @zuston @jerqi

Ok for me.
