### ISSUE TITLE
[Improvement] Process don't exit if exec start script using ansible

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#79]
Process don't exit if exec start script using ansible. Therefore, we can't do batch start operation for this.

**Comment by zuston** [comment]
+1. We have similar problem.

**Comment by jerqi** [comment]
Do you have the solution of the problem?

**Comment by xianjingfeng** [comment]
Yes, by using nohup

**Comment by jerqi** [comment]
Do you want to raise a pr?

**Comment by xianjingfeng** [comment]
> Do you want to raise a pr?

yes
