### ISSUE TITLE
[FEATURE] Client reports task failure to coordinator

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#790]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

We'd better to introduce the new api for client to report task failure to coordinator.
If so, we could benefit as following.
1. collect this reporting as metric to know more about uniffle cluster
2. more easier to find exception from task 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
cc @xumanbu @advancedxy @smallzhongfeng @jerqi

**Comment by smallzhongfeng** [comment]
I think it does make sense.

**Comment by jerqi** [comment]
Maybe we need a dashboard process instead of reporting failures to Coordinator.
