### ISSUE TITLE
[Improvement] Implement the interface ShuffleDataIO

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#802]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We can implement ShuffleDataIO
https://github.com/apache/spark/blob/master/core/src/main/java/org/apache/spark/shuffle/api/ShuffleDataIO.java
https://github.com/apache/spark/blob/master/core/src/main/java/org/apache/spark/shuffle/api/ShuffleDriverComponents.java
Dynamic Allocation don't need patch any more.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Kwafoor** [comment]
I'm Interested in this, could you assign it to me？

**Comment by jerqi** [comment]
> I'm Interested in this, could you assign it to me？

OK, I have assigned to you.

**Comment by Kwafoor** [comment]
The patch [SPARK-42689] that allows ShuffleDriverComponent to declare if shuffle data is reliably stored has been fixed in Spark 3.5, which has not yet been released. Do I need to test it?

**Comment by jerqi** [comment]
Yes, you can build a spark client with master branch to test it.

**Comment by Kwafoor** [comment]
> Yes, you can build a spark client with master branch to test it.

Okay, I will do that.

**Comment by summaryzb** [comment]
volunteering

**Comment by jerqi** [comment]
@Kwafoor If you're busy recently, let @summaryzb finish this issue first.
