### ISSUE TITLE
[Umbrella] Dynamic shuffle server assignment

### ISSUE THREAD

**Issue by advancedxy** [apache/incubator-uniffle#825]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.

### Describe the proposal

Currently, the shuffle server assignment info(for spark) is created when the shuffle is registered on driver side. `RssShuffleHandleInfo` holds the assignment info and is immutable. Therefore, the shuffle server assignment info is static. This simplifies reader and writer implementation which sacrifices flexibility.

When developing #477, there's one piece left to fully enable stage re-submit: regenerating the shuffle server assignments when the whole stage is re-submitted.

In this proposal, I'd like to propose to support dynamic shuffle server assignments during stage resubmission or detecting bad shuffle servers on the fly.

To archive that, there are some parts needs to be updated:
1. add new interfaces to ShufffleManagerGrpcService to generate shuffle server assignment dynamically
2. Corresponding ShuffleManagerClient
3. ShuffleRead/Write client and RssShuffleManager which eliminate the use of `RssShuffleHandleInfo`
4. Rethought/rework of reader's data check part
5. Maybe a unified and static shuffle client to share shuffle assignments, otherwise it would be costly to retrieve shuffle assignments for each task.

### Task list

TBD

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
Really looking forward this. Thanks @advancedxy in advance. 😺

**Comment by zjf2012** [comment]
Maybe we can increase the granularity of partitions->shuffle servers mappings to reduce overhead. Instead of mapping per partition, we can map by partition range or partition hash/modulo.

Just my piece of thought.

**Comment by jerqi** [comment]
A critical problem is that how to inform the servers that we will assign a new server.

**Comment by xumanbu** [comment]
> 



> Maybe we can increase the granularity of partitions->shuffle servers mappings to reduce overhead. Instead of mapping per partition, we can map by partition range or partition hash/modulo.
> 
> Just my piece of thought.

+1. we can assgin shuffle server seq for per partition,when the first server is unhealthy or crashed, the second server will served for this parition.

**Comment by jerqi** [comment]
> > A critical problem is that how to inform the servers that we will assign a new server.
> 
> `inform the servers` what servers do you mean?

I mean that we should how to inform the executors that we have updated shuffle servers. Do we only know the shuffle server allocation at the beginning of the stage or the beginning of the stage re-attempt? Could we add shuffle server for some partitions when the stage is running? If we can, how to inform the executors that we have assign new shuffle servers?

**Comment by jerqi** [comment]
> > > > A critical problem is that how to inform the servers that we will assign a new server.
> > > 
> > > 
> > > `inform the servers` what servers do you mean?
> > 
> > 
> > I mean that we should how to inform the executors that we have updated shuffle servers. Do we only know the shuffle server allocation at the beginning of the stage or the beginning of the stage re-attempt? Could we add shuffle server for some partitions when the stage is running? If we can, how to inform the executors that we have assign new shuffle servers?
> 
> Each task will retrieve new shuffle assignment from driver with local cache on the executor side. So once a new server is added, new tasks will get new shuffle server assignments. Old tasks wouldn't get a chance to update shuffle server assignments. It would either failed/abort due to bad shuffle server or write shuffle data successfully.

Will it cause too much pressure if we don't executor's level shuffle server info cache.

**Comment by zjf2012** [comment]
> > Maybe we can increase the granularity of partitions->shuffle servers mappings to reduce overhead. Instead of mapping per partition, we can map by partition range or partition hash/modulo.
> > Just my piece of thought.
> 
> could you elaborate a bit more? We were considering partition range, but it's not that effective. We may reconsider in the near feature.
> 
> Even the partitions are grouped in ranges, the partition to server mapping still would be a complete view of all partitions/ranges.

Have you tried the Java TreeMap? It's a good candidate for range search instead of maintaining partitions/ranges map. Please check https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html#higherEntry-K-. Keys are range values. Values are servers.

**Comment by yl09099** [comment]
@advancedxy @jerqi We need the implementation of this function, could you please assign this issue to me.

**Comment by jerqi** [comment]
> @advancedxy @jerqi We need the implementation of this function, could you please assign this issue to me.

Thanks

**Comment by zuston** [comment]
Any process? I think this is a huge improvement for uniffle. @yl09099

**Comment by yl09099** [comment]
> Any process? I think this is a huge improvement for uniffle. @yl09099

The development has been completed and the integration test is under way. I will submit it for review tomorrow or the day after tomorrow

**Comment by zuston** [comment]
> > Any process? I think this is a huge improvement for uniffle. @yl09099
> 
> The development has been completed and the integration test is under way. I will submit it for review tomorrow or the day after tomorrow

Awesome! Do you mind publishing a draft design doc for me? I'm so glad to review this.

**Comment by zuston** [comment]
Can we disable this dynamic assignment manually ? @yl09099
