### ISSUE TITLE
[Improvement] Add a similar util method like ThreadUtils.parmap in the Spark

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#851]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We usaully use multiple threads to send rpc requests, we should have a method similar to https://github.com/apache/spark/blob/d157b2d9a71c8370612342b298f0e6757c9b9b78/core/src/main/scala/org/apache/spark/util/ThreadUtils.scala#LL388C11-L388C11
Uniffle have similar logic in many places, like
https://github.com/apache/incubator-uniffle/blob/a3ca2585487265cf791d5a0c6f401041eb3f4b55/client/src/main/java/org/apache/uniffle/client/impl/ShuffleWriteClientImpl.java#L744
We can add a method parmap in the ThreadUtil to reduce repeated logic.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
> Can you assign to me this issue? Thank you very much!

You can also refer to the implement of Iceberg   https://github.com/apache/iceberg/blob/9f12b85667362dbf0cc1bbb16972602a103938a8/core/src/main/java/org/apache/iceberg/util/Tasks.java#L294

**Comment by zhuyaogai** [comment]
> Can you assign to me this issue? Thank you very much!

@zhtttylz hi, are you still working on this issue? May I pr for this issue?

**Comment by zhtttylz** [comment]
> > Can you assign to me this issue? Thank you very much!
> 
> @zhtttylz hi, are you still working on this issue? May I pr for this issue?

 I will work on this PR as soon as possible :)
