### ISSUE TITLE
[Feature] Introduce graceful decommission for shuffle server

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#86]
When shuffle servers needed to decommission are included in exclude-node-files, we hope shuffle server will exit by its own when all apps finished.

Draft PR: #85

**Comment by jerqi** [comment]
Why don't we reuse the issue #80? In my opinion, it's duplicate issue.

**Comment by zuston** [comment]
Sorry i miss previous issue. Merge this topic to #80
