### ISSUE TITLE
[Improvement] Default value optimization for 0.8

### ISSUE THREAD

**Issue by jerqi** [apache/incubator-uniffle#889]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We have developed features to improve the performance of Uniffle. But most of them are turned off by default. Now we will prefer to turn on some config options by default.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
```
rss.server.single.buffer.flush.enabled true
rss.server.single.buffer.flush.threshold 128M
```
```
rss.coordinator.select.partition.strategy CONTINUOUS
```

**Comment by leixm** [comment]
> Maybe we can make these parameters as default value. @leixm These config options are related to you. Could you raise three pull requests to modify them one by one? (1)
> 
> ```
> rss.server.single.buffer.flush.enabled true
> rss.server.single.buffer.flush.threshold 128M
> ```
> 
> (2)
> 
> ```
> rss.coordinator.select.partition.strategy CONTINUOUS
> ```
> 
> (3)
> 
> ```
> rss.server.max.concurrency.of.per-partition.write 30
> ```

Sure, i will raise PRs later.

**Comment by zuston** [comment]
I will make the client compress type as ZSTD by default.

**Comment by jerqi** [comment]
> I will make the client compress type as ZSTD by default. cc @jerqi

It's ok for me if we have verified in the production environment.

**Comment by zuston** [comment]
> > I will make the client compress type as ZSTD by default. cc @jerqi
> 
> It's ok for me if we have verified in the production environment.

ZSTD has been applied in our production for 1 year by default

**Comment by jerqi** [comment]
> > > I will make the client compress type as ZSTD by default. cc @jerqi
> > 
> > 
> > It's ok for me if we have verified in the production environment.
> 
> ZSTD has been applied in our production for 1 year by default

OK.
