### ISSUE TITLE
[Improvement] Rename Hdfs*.java to Hadoop*.java to support other Hadoop FS-compatible distributed filesystem

### ISSUE THREAD

**Issue by jiafuzha** [apache/incubator-uniffle#895]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In server and storage modules, there are many classes prefixed with Hdfs which use Hadoop FS API and are thus impl agnostic, not depending on specific Hdfs impl. So, it's better to rename them to Hadoop* so that we can support other Hadoop FS compatible distributed filesystem by extending existing classes. It'll make code look more naturally. 

There may be some slight differences among different Hadoop FS impls, like [hadoop-daos](https://github.com/daos-stack/daos/tree/master/src/client/java/hadoop-daos) not have a dedicated thread for reading and writing data, which is different from hdfs. Thus, we don't need to close outputstream at each flush to FS. 

### How should we improve?

Just rename the class names.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zjf2012** [comment]
@advancedxy @jerqi does it look reasonable for you?

**Comment by zuston** [comment]
Sounds good

**Comment by jerqi** [comment]
OK for me.
