### ISSUE TITLE
[Bug] wrong answer when join key is chinese string.

### ISSUE THREAD

**Issue by lifeSo** [apache/incubator-uniffle#910]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

wrong answer when join key is chinese string.

### Affects Version(s)

master

### Uniffle Server Log Output

```logtalk
wrong answer when join key is chinese string.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Solved.
