### ISSUE TITLE
[Improvement ] Add rest api for shuffle server list of lost connection and unhealthy

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#937]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

Obtain the list of ServerNodes whose heartbeat is lost from a Coordinator Server,
Obtain the list of ServerNodes whose unhealthy  from a Coordinator Server

### Affects Version(s)

0.8.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
If you want to add an extra api, you would better add a rest api. You can refer to https://github.com/apache/incubator-uniffle/pull/931

**Comment by yl09099** [comment]
@jerqi I changed the title, I just want to add the rest api
