### ISSUE TITLE
[FEATURE] Support integrationing into gluten

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#940]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

`gluten` is a spark native engine. When we integrate uniffle into gluten, we need to adjust some codes of uniffle.
In addition, we also need to publish the jar package to the public maven warehouse, like `celeborn` done.
https://github.com/oap-project/gluten/tree/main/gluten-celeborn

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xianjingfeng** [comment]
@kaijchen Can you help publish the jar package to the public maven repository.
And my colleagues will help complete the remaining work of this feature.

**Comment by xianjingfeng** [comment]
cc @jerqi @advancedxy @zuston

**Comment by jerqi** [comment]
> @kaijchen Can you help publish the jar package to the public maven repository. And my colleagues will help complete the remaining work of this feature.

If we want to publish the jar package, we need to finish binary release. And we only finish source release. We can discuss this issue on Uniffle regular meeting in  the next week.

**Comment by kaijchen** [comment]
> @kaijchen Can you help publish the jar package to the public maven repository.

Doing so might require releasing process, let's do it in release 0.7.1?
Or we can publish the artifacts to the SNAPSHOT repository.

**Comment by jerqi** [comment]
cc @summaryzb

**Comment by xianjingfeng** [comment]
> > @kaijchen Can you help publish the jar package to the public maven repository.
> 
> Doing so might require releasing process, let's do it in release 0.7.1? Or we can publish the artifacts to the SNAPSHOT repository.

We can do it in next release version, after we finish complete this feature.

**Comment by summaryzb** [comment]
I‘d like to involve this feature, shall you open a discussion on it

**Comment by zuston** [comment]
SGTM.

**Comment by summaryzb** [comment]
we implement the integration in our production pipeline as below
<img width="783" alt="image" src="https://github.com/apache/incubator-uniffle/assets/37905939/7eac97c7-5e5d-48bf-85a5-77476e180e5f">

**Comment by summaryzb** [comment]
gluten side change
https://github.com/oap-project/gluten/pull/1966

**Comment by jerqi** [comment]
@summaryzb Could you write a simple document like https://docs.google.com/document/d/1G0cOFVJbYLf2oX1fiadh7zi2M6DlEcjTQTh4kSkb0LA/edit#heading=h.kl0vgpq0nxcy
? It's more easy if other people want to join the discussion or study the implement of this feature.

**Comment by summaryzb** [comment]
Sure I'll post it here today later
