### ISSUE TITLE
[Improvement] Add the HADOOP_VERSION to the RSS Server image name by default

### ISSUE THREAD

**Issue by connorlwilkes** [apache/incubator-uniffle#951]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now that Uniffle supports more than just Hadoop 2.x it would make sense to tag built docker images with the Hadoop version as well as the rss version.

### How should we improve?

Just append to build.sh with HADOOP_VERSION in the image name

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
OK for me. You can go ahead.

**Comment by connorlwilkes** [comment]
I think we can just ignore the minor hadoop version so we treat Hadoop 3.2.4 as hadoop3.2 and the resulting image would be something like `0.8.0-SNAPSHOT-hadoop3.2-<git-commit>`?

**Comment by connorlwilkes** [comment]
I would be fixing build.sh as currently it doesn't get the right RSS_VERSION as it has not been updated to pick it up as per https://github.com/apache/incubator-uniffle/blob/master/build_distribution.sh#L130
