### ISSUE TITLE
[Umbrella] Uniffle needs to add a WebUI page

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#960]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the proposal

Add a webUI management module for Uniffle, and view specific functions：https://docs.google.com/document/d/10IEbbo_xQS-GHy0ezRcm9mT4Fv9hqghDsXivDpK1kas/edit

### Task list
    1、The code structure of the webUI module needs to be set up.
    2、Front-end pages for the Development Coordinator, ShuffleServer, and Applicantion.
    3、Coordinator, ShuffleServer, and Application back-end RESTful interface development.
    4、Deployment scripts for WebAPP and start script development.

**Comment by zuston** [comment]
Great idea! Maybe we need a proposal to show the UI draft.

**Comment by yl09099** [comment]
@zuston At present, I have opened three pages according to my own ideas. I hope you can put forward your ideas and we can discuss them together. Thank you

**Comment by zuston** [comment]
Wow, it's great, how about discuss this in our weekend meeting firstly?

**Comment by yl09099** [comment]
OK @zuston

**Comment by jerqi** [comment]
> OK @zuston

Have you joined our Wechat group? The regular meeting link is in the group announcement.

**Comment by yl09099** [comment]
@jerqi I haven't joined the wechat group, how can I join?

**Comment by jerqi** [comment]
![9ea34cef3d263ebb1bb28b6d0978c2bd](https://github.com/apache/incubator-uniffle/assets/8159038/a4f608aa-0550-4a7d-b64b-62ed9558bf58)

**Comment by slfan1989** [comment]
@jerqi @zuston @yl09099 Shouldn't we find a professional frontend developer to review this design and validate its feasibility?

We lack experience in frontend development, and we haven't compared the design of this web module with other projects. This makes me concerned about the module's overall applicability.

**Comment by jerqi** [comment]
> @jerqi @zuston @yl09099 Shouldn't we find a professional frontend developer to review this design and validate its feasibility?
> 
> We lack experience in frontend development, and we haven't compared the design of this web module with other projects. This makes me concerned about the module's overall applicability.

Yes, we would better have  professional frontend developer. But we don't have them now.  Some projects also propose a simple dashboard. As the project's development, it will attract some professional frontend developers. The frontend developers will refactor dashboard. So we can propose a simple UI dashboard first.

**Comment by zuston** [comment]
Is it possible to support multiple coordinator in one dashboard server? @yl09099

**Comment by yl09099** [comment]
> Is it possible to support multiple coordinator in one dashboard server? @yl09099

After I finish fixing the bug, I will modify it, so it can be done at present.
