### ISSUE TITLE
[Improvement] feat(coordinator): log4j CVE problems

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#967]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Introduced the Hadoop-common-2.8.5 package of hadoop, introduced the log4j log package, version 1.2.17, this version has serious cve problems：https://mvnrepository.com/artifact/log4j/log4j/1.2.17

### How should we improve?

You need to exclude the log4j package and introduce a later version of the log4j package

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yl09099** [comment]
@jerqi Take a look at this question.Please!

**Comment by jerqi** [comment]
We only use Hadoop dependency in our test code. We won't include the hadoop jar in our release package.
