### ISSUE TITLE
[Improvement] Introduce config to customize assignment server numbers in client side

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#97]
### Motivation
Now the assignment number specified by coordinator's conf of `rss.coordinator.shuffle.nodes.max`. But i think it's not suitable for all spark jobs. 

We should introduce new config to let client specify the assignment server number. `rss.coordinator.shuffle.nodes.max` should be as a max limitation of clients' number.

**Comment by jerqi** [comment]
Make sense.

**Comment by zuston** [comment]
I will take it and submit PR later.

**Comment by zuston** [comment]
PR #100

**Comment by jerqi** [comment]
Solved by #100
